//! Consumer gateway deployment and G2G routing verification.
//!
//! Deploys a consumer Praxis AI gateway into the first consumer-role cluster
//! defined in the environment config, configures it with a static
//! `grid_route` stanza derived from provider site/model declarations, and
//! verifies that all configured models route correctly through the consumer.
//!
//! Provider endpoints are reached via `NodePort` over the kind Docker bridge.
//! Mutual TLS uses certificates generated by `xtask env up` and stored under
//! `tests/env/certs/`.

use std::{
    net::TcpStream,
    path::PathBuf,
    process::Command,
    time::{Duration, Instant},
};

use crate::env::{
    config::{ClusterDef, ClusterRole, EnvConfig},
    images::GATEWAY_IMAGE,
    kind::kubectl_context,
    verify::{HttpResponse, PortForwardGuard, Tally, find_free_port, parse_curl_output, safe_truncate, wait_for_port},
};

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/// Kubernetes namespace for consumer deployments.
const NAMESPACE: &str = "default";

/// Gateway HTTP port.
const GATEWAY_HTTP_PORT: u16 = 8080;

/// `NodePort` range minimum for provider gateway exposure.
const NODE_PORT_BASE: u16 = 30080;

/// Rollout timeout in seconds.
const ROLLOUT_TIMEOUT_SECS: u32 = 120;

/// Network probe timeout.
const PROBE_TIMEOUT: Duration = Duration::from_secs(5);

/// K8s Secret name holding TLS certs for the consumer gateway pod.
const TLS_SECRET_NAME: &str = "praxis-tls";

/// Path inside the consumer pod where TLS certs are mounted.
const CERT_MOUNT_PATH: &str = "/etc/praxis/tls";

/// Host-side cert directory (relative to workspace root).
const HOST_CERTS_DIR: &str = "tests/env/certs";

// ---------------------------------------------------------------------------
// Consumer cluster resolution
// ---------------------------------------------------------------------------

/// Resolve the consumer cluster name from the environment config.
///
/// Returns the name of the first cluster declared with
/// [`ClusterRole::Consumer`].  Returns an error if no consumer cluster is
/// configured.
fn consumer_cluster_name(cfg: &EnvConfig) -> Result<&str, Box<dyn std::error::Error>> {
    cfg.clusters
        .names
        .iter()
        .find(|name| {
            cfg.clusters
                .definitions
                .get(*name)
                .is_some_and(|d| d.role == ClusterRole::Consumer)
        })
        .map(String::as_str)
        .ok_or_else(|| "no consumer cluster configured in environment config".into())
}

// ---------------------------------------------------------------------------
// Network probe
// ---------------------------------------------------------------------------

/// Probe cross-kind network connectivity from the consumer cluster to all
/// provider gateways.
///
/// Outputs a PASS/FAIL/INFO report for each provider's node IP, `NodePort`
/// reachability, and Docker network adjacency.
///
/// # Errors
///
/// Returns an error only for fatal infrastructure failures.
pub(crate) fn probe_network(cfg: &EnvConfig) -> Result<(), Box<dyn std::error::Error>> {
    eprintln!("Probing cross-kind network connectivity...");
    eprintln!();

    let consumer_site = consumer_cluster_name(cfg)?;
    let consumer_ctx = kubectl_context(consumer_site);

    for name in &cfg.clusters.names {
        let Some(def) = cfg.clusters.definitions.get(name) else {
            continue;
        };
        if def.role != ClusterRole::Provider {
            continue;
        }
        probe_provider_reachability(name, def, &consumer_ctx)?;
    }

    Ok(())
}

/// Probe whether a provider cluster's gateway is reachable from the consumer.
#[expect(clippy::too_many_lines, reason = "sequential probe steps with diagnostic output")]
fn probe_provider_reachability(
    provider: &str,
    _def: &ClusterDef,
    consumer_ctx: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    let provider_ctx = kubectl_context(provider);

    let node_ip = get_kind_node_ip(&provider_ctx)?;
    eprintln!("  provider {provider} kind node IP: {node_ip}");

    let node_port = get_nodeport(&provider_ctx, "praxis-provider");
    match node_port {
        Some(port) => {
            eprintln!("  provider {provider} NodePort: {port}");
            let addr = format!("{node_ip}:{port}");
            let reachable = probe_tcp(&addr);
            if reachable {
                eprintln!("  [PASS] {provider} gateway {addr} reachable from host");
            } else {
                eprintln!(
                    "  [INFO] {provider} gateway {addr} not reachable from host \
                     (may still work from inside cluster)"
                );
            }
        },
        None => {
            eprintln!(
                "  [INFO] {provider} gateway has no NodePort; \
                 will use port-forward from consumer"
            );
        },
    }

    let same_network = check_docker_network(&provider_ctx, consumer_ctx)?;
    if same_network {
        eprintln!("  [PASS] provider and consumer kind nodes share a Docker network");
    } else {
        eprintln!("  [WARN] provider and consumer kind nodes may be on different Docker networks");
        eprintln!("         Cross-cluster routing may require NodePort exposure and host-level access");
    }

    println!();
    Ok(())
}

/// Get the Docker IP of the first kind node in a cluster.
fn get_kind_node_ip(context: &str) -> Result<String, Box<dyn std::error::Error>> {
    let output = Command::new("kubectl")
        .args([
            "--context",
            context,
            "get",
            "nodes",
            "-o",
            "jsonpath={.items[0].status.addresses[?(@.type==\"InternalIP\")].address}",
        ])
        .output()?;
    let ip = String::from_utf8(output.stdout)?.trim().to_owned();
    if ip.is_empty() {
        return Err(format!("could not get node IP for context {context}").into());
    }
    Ok(ip)
}

/// Get the `NodePort` for a service if it is exposed as `NodePort`.
fn get_nodeport(context: &str, service: &str) -> Option<u16> {
    let output = Command::new("kubectl")
        .args([
            "--context",
            context,
            "get",
            "service",
            service,
            "-n",
            NAMESPACE,
            "-o",
            "jsonpath={.spec.ports[0].nodePort}",
        ])
        .output()
        .ok()?;
    let port_str = String::from_utf8(output.stdout).ok()?;
    port_str.trim().parse().ok().filter(|&p: &u16| p > 0)
}

/// Probe a TCP address.
#[expect(
    clippy::disallowed_methods,
    reason = "synchronous networking probe; no async runtime available"
)]
fn probe_tcp(addr: &str) -> bool {
    let deadline = Instant::now() + PROBE_TIMEOUT;
    loop {
        if TcpStream::connect(addr).is_ok() {
            return true;
        }
        if Instant::now() >= deadline {
            return false;
        }
        std::thread::sleep(Duration::from_millis(500));
    }
}

/// Check whether provider and consumer kind nodes share a Docker network.
fn check_docker_network(provider_ctx: &str, consumer_ctx: &str) -> Result<bool, Box<dyn std::error::Error>> {
    let provider_node = get_node_name(provider_ctx)?;
    let consumer_node = get_node_name(consumer_ctx)?;
    let provider_nets = get_docker_networks(&provider_node);
    let consumer_nets = get_docker_networks(&consumer_node);
    Ok(provider_nets.iter().any(|n| consumer_nets.contains(n)))
}

/// Get the first node name in a cluster.
fn get_node_name(context: &str) -> Result<String, Box<dyn std::error::Error>> {
    let output = Command::new("kubectl")
        .args([
            "--context",
            context,
            "get",
            "nodes",
            "-o",
            "jsonpath={.items[0].metadata.name}",
        ])
        .output()?;
    Ok(String::from_utf8(output.stdout)?.trim().to_owned())
}

/// Get Docker network names for a container (kind node).
fn get_docker_networks(container: &str) -> Vec<String> {
    Command::new("docker")
        .args([
            "inspect",
            "--format",
            "{{range $k,$v := .NetworkSettings.Networks}}{{$k}}\n{{end}}",
            container,
        ])
        .output()
        .ok()
        .and_then(|o| String::from_utf8(o.stdout).ok())
        .unwrap_or_default()
        .lines()
        .map(str::to_owned)
        .collect()
}

// ---------------------------------------------------------------------------
// Consumer gateway deployment
// ---------------------------------------------------------------------------

/// Deploy the consumer gateway.
///
/// Resolves the consumer cluster from the environment config, collects
/// provider `NodePort` endpoints, creates the TLS secret from locally
/// generated certificates, applies a static `grid_route` `ConfigMap`, and
/// deploys the Praxis AI gateway Deployment and Service.
///
/// # Errors
///
/// Returns an error if the consumer cluster is not configured, no provider
/// gateway endpoints are found, or any Kubernetes apply fails.
pub(crate) fn deploy_consumer(cfg: &EnvConfig) -> Result<(), Box<dyn std::error::Error>> {
    let consumer_site = consumer_cluster_name(cfg)?;
    let consumer_ctx = kubectl_context(consumer_site);
    eprintln!("  deploying consumer gateway to {consumer_ctx}...");

    let provider_endpoints = collect_provider_endpoints(cfg)?;
    if provider_endpoints.is_empty() {
        return Err("no provider gateway endpoints found".into());
    }

    create_consumer_tls_secret(&consumer_ctx, consumer_site)?;
    apply_consumer_config(&consumer_ctx, consumer_site, &provider_endpoints)?;
    apply_consumer_deployment(&consumer_ctx)?;

    wait_for_rollout(&consumer_ctx, "praxis-consumer", consumer_site)?;

    eprintln!("  [PASS] consumer gateway ready in {consumer_ctx}");
    Ok(())
}

/// Collect provider gateway endpoints for consumer routing.
///
/// Tries to get `NodePort` addresses for each provider cluster.
/// If no `NodePort` exists, exposes one.
fn collect_provider_endpoints(cfg: &EnvConfig) -> Result<Vec<ProviderEndpoint>, Box<dyn std::error::Error>> {
    let mut endpoints = Vec::new();
    for name in &cfg.clusters.names {
        let Some(def) = cfg.clusters.definitions.get(name) else {
            continue;
        };
        if def.role != ClusterRole::Provider || def.models.is_empty() {
            continue;
        }
        endpoints.push(resolve_provider_endpoint(name, def)?);
    }
    for ep in &endpoints {
        eprintln!(
            "  provider endpoint: {} @ {} (models: {})",
            ep.site,
            ep.address,
            ep.models.join(", ")
        );
    }
    Ok(endpoints)
}

/// Resolve the reachable endpoint for one provider cluster.
fn resolve_provider_endpoint(name: &str, def: &ClusterDef) -> Result<ProviderEndpoint, Box<dyn std::error::Error>> {
    let ctx = kubectl_context(name);
    let node_port = if let Some(p) = get_nodeport(&ctx, "praxis-provider") {
        p
    } else {
        eprintln!("  [WARN] no NodePort for {name}; exposing via NodePort now...");
        expose_gateway_nodeport(&ctx, name)?;
        get_nodeport(&ctx, "praxis-provider").unwrap_or(NODE_PORT_BASE)
    };
    let node_ip = get_kind_node_ip(&ctx).unwrap_or_else(|_| "127.0.0.1".to_owned());
    Ok(ProviderEndpoint {
        site: name.to_owned(),
        address: format!("{node_ip}:{node_port}"),
        models: def.models.clone(),
        sni: format!("{name}.grid.internal"),
    })
}

/// Expose a provider gateway as `NodePort` if not already exposed.
fn expose_gateway_nodeport(context: &str, site: &str) -> Result<(), Box<dyn std::error::Error>> {
    let status = Command::new("kubectl")
        .args([
            "--context",
            context,
            "-n",
            NAMESPACE,
            "patch",
            "service",
            "praxis-provider",
            "-p",
            &format!(
                r#"{{"spec":{{"type":"NodePort","ports":[{{"port":{GATEWAY_HTTP_PORT},"targetPort":{GATEWAY_HTTP_PORT},"nodePort":{NODE_PORT_BASE}}}]}}}}"#
            ),
        ])
        .status()?;
    if !status.success() {
        return Err(format!("failed to patch praxis-provider service in {site}").into());
    }
    Ok(())
}

/// Provider endpoint resolved for consumer routing.
struct ProviderEndpoint {
    /// Site name (matches the provider cluster name).
    site: String,
    /// Reachable `host:port` address for the provider gateway.
    address: String,
    /// Configured model names for this provider.
    models: Vec<String>,
    /// TLS SNI hostname (used in future mTLS extensions).
    #[expect(dead_code, reason = "future mTLS extension point")]
    sni: String,
}

/// Create (or update) the TLS secret in the consumer cluster.
///
/// Loads the locally-generated certificate for `consumer_site`, its private
/// key, and the local CA certificate from `tests/env/certs/`.  These are
/// created by `xtask env up`.
fn create_consumer_tls_secret(context: &str, consumer_site: &str) -> Result<(), Box<dyn std::error::Error>> {
    let certs_dir = PathBuf::from(HOST_CERTS_DIR);
    let cert = certs_dir.join(format!("{consumer_site}-cert.pem"));
    let key = certs_dir.join(format!("{consumer_site}-key.pem"));
    let ca = certs_dir.join("ca.pem");

    eprintln!("  creating TLS secret in {context}...");

    let output = Command::new("kubectl")
        .args([
            "create",
            "secret",
            "generic",
            TLS_SECRET_NAME,
            &format!("--from-file=tls.crt={}", cert.display()),
            &format!("--from-file=tls.key={}", key.display()),
            &format!("--from-file=ca.crt={}", ca.display()),
            "--namespace",
            NAMESPACE,
            "--dry-run=client",
            "-o",
            "yaml",
        ])
        .output()?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(format!("kubectl create secret failed: {stderr}").into());
    }

    let yaml = String::from_utf8(output.stdout)?;
    apply_manifest(context, &yaml)
}

/// Apply the consumer gateway `ConfigMap`.
fn apply_consumer_config(
    context: &str,
    consumer_site: &str,
    providers: &[ProviderEndpoint],
) -> Result<(), Box<dyn std::error::Error>> {
    let config = consumer_gateway_config(consumer_site, providers);
    let yaml = format!(
        "apiVersion: v1\n\
         kind: ConfigMap\n\
         metadata:\n\
         \x20 name: praxis-consumer-config\n\
         \x20 namespace: {NAMESPACE}\n\
         data:\n\
         \x20 praxis.yaml: |\n\
         {}\n",
        indent_yaml(&config, 4)
    );
    apply_manifest(context, &yaml)
}

/// Build the consumer Praxis config YAML.
///
/// Generates a static `grid_route` stanza from the supplied `consumer_site`
/// (used as `local_site`) and `providers` (one candidate per model per site).
/// A `load_balancer` section provides mTLS cluster definitions for each
/// provider.  A catch-all `router` route falls through to the first provider
/// cluster for requests without a recognised model header.
///
/// The `grid_route` cluster convention is `gateway-{site}`, which must match
/// the names produced by [`build_clusters`].
#[expect(clippy::too_many_lines, reason = "Praxis config YAML generation")]
fn consumer_gateway_config(consumer_site: &str, providers: &[ProviderEndpoint]) -> String {
    let candidates = build_grid_route_candidates(providers);
    let clusters = build_clusters(providers);
    let fallback = providers
        .first()
        .map_or_else(|| std::process::abort(), |ep| format!("gateway-{}", ep.site));

    format!(
        "listeners:\n\
         \x20 - name: public\n\
         \x20   address: \"0.0.0.0:{GATEWAY_HTTP_PORT}\"\n\
         \x20   filter_chains:\n\
         \x20     - consumer-chain\n\
         filter_chains:\n\
         \x20 - name: consumer-chain\n\
         \x20   filters:\n\
         \x20     - filter: json_body_field\n\
         \x20       field: model\n\
         \x20       header: X-Model\n\
         \x20     - filter: grid_route\n\
         \x20       local_site: {consumer_site}\n\
         \x20       model_header: X-Model\n\
         \x20       candidates:\n\
         {candidates}\n\
         \x20     - filter: router\n\
         \x20       routes:\n\
         \x20         - path_prefix: \"/\"\n\
         \x20           cluster: {fallback}\n\
         \x20     - filter: load_balancer\n\
         \x20       clusters:\n\
         {clusters}\n\
         admin:\n\
         \x20 address: \"127.0.0.1:9901\"\n\
         shutdown_timeout_secs: 5\n"
    )
}

/// Build `grid_route` candidate entries from provider endpoints.
///
/// Each `(model, site)` pair becomes one `inference_model` candidate.
/// The cluster name is `gateway-{site}`, matching the `load_balancer` section.
fn build_grid_route_candidates(providers: &[ProviderEndpoint]) -> String {
    providers
        .iter()
        .flat_map(|ep| {
            ep.models.iter().map(move |m| {
                format!(
                    "\x20\x20\x20\x20\x20\x20\x20\x20 - kind: inference_model\n\
                     \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20 name: {m}\n\
                     \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20 site: {}\n\
                     \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20 cluster: gateway-{}",
                    ep.site, ep.site
                )
            })
        })
        .collect::<Vec<_>>()
        .join("\n")
}

/// Build `load_balancer` cluster entries for each provider.
///
/// Each cluster uses mTLS: the consumer presents its locally-generated client
/// certificate, and verifies the provider server certificate against the
/// locally-generated CA.  SNI is set to `{site}.grid.internal` which must
/// match the Subject Alternative Name in the provider's server certificate.
fn build_clusters(providers: &[ProviderEndpoint]) -> String {
    providers
        .iter()
        .map(|ep| {
            [
                format!("         - name: gateway-{}", ep.site),
                "           tls:".to_owned(),
                "             ca:".to_owned(),
                format!("               ca_path: {CERT_MOUNT_PATH}/ca.crt"),
                "             client_cert:".to_owned(),
                format!("               cert_path: {CERT_MOUNT_PATH}/tls.crt"),
                format!("               key_path: {CERT_MOUNT_PATH}/tls.key"),
                format!("             sni: {}.grid.internal", ep.site),
                "             verify: true".to_owned(),
                "           endpoints:".to_owned(),
                format!("             - \"{}\"", ep.address),
            ]
            .join("\n")
        })
        .collect::<Vec<_>>()
        .join("\n")
}

/// Apply the consumer gateway Deployment and Service.
#[expect(clippy::too_many_lines, reason = "K8s manifest generation")]
fn apply_consumer_deployment(context: &str) -> Result<(), Box<dyn std::error::Error>> {
    let yaml = format!(
        "apiVersion: apps/v1\n\
         kind: Deployment\n\
         metadata:\n\
         \x20 name: praxis-consumer\n\
         \x20 namespace: {NAMESPACE}\n\
         spec:\n\
         \x20 replicas: 1\n\
         \x20 selector:\n\
         \x20   matchLabels:\n\
         \x20     app: praxis-consumer\n\
         \x20 template:\n\
         \x20   metadata:\n\
         \x20     labels:\n\
         \x20       app: praxis-consumer\n\
         \x20   spec:\n\
         \x20     containers:\n\
         \x20       - name: praxis-ai\n\
         \x20         image: {GATEWAY_IMAGE}\n\
         \x20         imagePullPolicy: Never\n\
         \x20         ports:\n\
         \x20           - containerPort: {GATEWAY_HTTP_PORT}\n\
         \x20         args:\n\
         \x20           - \"--config\"\n\
         \x20           - \"/etc/praxis/praxis.yaml\"\n\
         \x20         volumeMounts:\n\
         \x20           - name: config\n\
         \x20             mountPath: /etc/praxis\n\
         \x20             readOnly: true\n\
         \x20           - name: tls-certs\n\
         \x20             mountPath: {CERT_MOUNT_PATH}\n\
         \x20             readOnly: true\n\
         \x20     volumes:\n\
         \x20       - name: config\n\
         \x20         configMap:\n\
         \x20           name: praxis-consumer-config\n\
         \x20       - name: tls-certs\n\
         \x20         secret:\n\
         \x20           secretName: {TLS_SECRET_NAME}\n\
         ---\n\
         apiVersion: v1\n\
         kind: Service\n\
         metadata:\n\
         \x20 name: praxis-consumer\n\
         \x20 namespace: {NAMESPACE}\n\
         spec:\n\
         \x20 selector:\n\
         \x20   app: praxis-consumer\n\
         \x20 ports:\n\
         \x20   - port: {GATEWAY_HTTP_PORT}\n\
         \x20     targetPort: {GATEWAY_HTTP_PORT}\n"
    );
    apply_manifest(context, &yaml)
}

// ---------------------------------------------------------------------------
// E2E verification
// ---------------------------------------------------------------------------

/// Verify consumer-to-provider gateway routing end-to-end.
///
/// Port-forwards to the consumer gateway, then for each configured provider
/// model sends a Chat Completions request and asserts a 200 response with
/// valid JSON.  Also asserts that an unknown model fails cleanly (404 or 503).
///
/// # Errors
///
/// Returns an error if any assertion fails.
#[expect(clippy::too_many_lines, reason = "multi-cluster E2E verification loop")]
pub(crate) fn verify_e2e(cfg: &EnvConfig) -> Result<(), Box<dyn std::error::Error>> {
    let consumer_site = consumer_cluster_name(cfg)?;
    let mut tally = Tally::default();
    let ctx = kubectl_context(consumer_site);

    let port = find_free_port()?;
    let mut pf = PortForwardGuard::start(&ctx, "praxis-consumer", port, GATEWAY_HTTP_PORT)?;

    if !wait_for_port(port) {
        tally.fail(consumer_site, "consumer gateway reachable via port-forward", &ctx);
        pf.stop();
        return tally.print_summary();
    }
    tally.pass(consumer_site, "consumer gateway reachable via port-forward");

    for name in &cfg.clusters.names {
        let Some(def) = cfg.clusters.definitions.get(name) else {
            continue;
        };
        if def.role != ClusterRole::Provider {
            continue;
        }
        for model in &def.models {
            verify_consumer_model(&ctx, port, name, model, consumer_site, &mut tally);
        }
    }

    match send_consumer_request(port, "nonexistent-model-xyz") {
        Ok(resp) if resp.status == 404 || resp.status == 503 => {
            tally.pass(consumer_site, "unknown model fails cleanly via consumer gateway");
        },
        Ok(resp) => {
            tally.fail(
                consumer_site,
                &format!("unknown model returned {} (expected 404 or 503)", resp.status),
                &ctx,
            );
        },
        Err(e) => {
            tally.fail(consumer_site, &format!("unknown model request failed: {e}"), &ctx);
        },
    }

    pf.stop();
    tally.print_summary()
}

/// Verify a single model routes correctly from the consumer to a provider.
#[expect(clippy::too_many_lines, reason = "per-model assertion chain")]
#[expect(
    clippy::too_many_arguments,
    reason = "all args are distinct non-groupable identifiers"
)]
fn verify_consumer_model(
    context: &str,
    port: u16,
    provider: &str,
    model: &str,
    consumer_site: &str,
    tally: &mut Tally,
) {
    match send_consumer_request(port, model) {
        Ok(resp) if resp.status == 200 => {
            tally.pass(
                consumer_site,
                &format!("model {model} (from {provider}) returns 200 via consumer gateway"),
            );
            if let Ok(json) = serde_json::from_str::<serde_json::Value>(&resp.body) {
                if json.get("choices").is_some_and(serde_json::Value::is_array) {
                    tally.pass(
                        consumer_site,
                        &format!("model {model} response is valid Chat Completions JSON"),
                    );
                } else {
                    let excerpt = safe_truncate(&resp.body, 200);
                    tally.fail(
                        consumer_site,
                        &format!("model {model} response missing choices\n         body: {excerpt}"),
                        context,
                    );
                }
            }
        },
        Ok(resp) => {
            let excerpt = safe_truncate(&resp.body, 200);
            tally.fail(
                consumer_site,
                &format!(
                    "model {model} returned {} (expected 200)\n         body: {excerpt}",
                    resp.status
                ),
                context,
            );
        },
        Err(e) => {
            tally.fail(
                consumer_site,
                &format!("model {model} request via consumer failed: {e}"),
                context,
            );
        },
    }
}

/// Send a Chat Completions request to the consumer gateway.
fn send_consumer_request(port: u16, model: &str) -> Result<HttpResponse, Box<dyn std::error::Error>> {
    let url = format!("http://127.0.0.1:{port}/v1/chat/completions");
    let body = format!(r#"{{"model":"{model}","messages":[{{"role":"user","content":"hello"}}],"max_tokens":1}}"#);
    let output = Command::new("curl")
        .args([
            "-s",
            "-w",
            "\n%{http_code}",
            "--connect-timeout",
            "5",
            "--max-time",
            "15",
            "-X",
            "POST",
            "-H",
            "Content-Type: application/json",
            "-d",
            &body,
            &url,
        ])
        .output()?;
    parse_curl_output(&String::from_utf8(output.stdout)?)
}

// ---------------------------------------------------------------------------
// Shared helpers
// ---------------------------------------------------------------------------

/// Apply a Kubernetes YAML manifest via `kubectl apply -f -`.
fn apply_manifest(context: &str, yaml: &str) -> Result<(), Box<dyn std::error::Error>> {
    let mut child = Command::new("kubectl")
        .args(["--context", context, "apply", "-f", "-"])
        .stdin(std::process::Stdio::piped())
        .spawn()?;

    if let Some(stdin) = child.stdin.as_mut() {
        std::io::Write::write_all(stdin, yaml.as_bytes())?;
    }
    let status = child.wait()?;
    if !status.success() {
        return Err(format!("kubectl apply failed: {status}").into());
    }
    Ok(())
}

/// Wait for a Deployment rollout to complete.
fn wait_for_rollout(context: &str, deployment: &str, cluster: &str) -> Result<(), Box<dyn std::error::Error>> {
    let timeout = format!("{ROLLOUT_TIMEOUT_SECS}s");
    let resource = format!("deployment/{deployment}");
    eprintln!("  waiting for {deployment} in {cluster}...");
    let status = Command::new("kubectl")
        .args([
            "--context",
            context,
            "-n",
            NAMESPACE,
            "rollout",
            "status",
            &resource,
            "--timeout",
            &timeout,
        ])
        .status()?;
    if !status.success() {
        return Err(format!("{deployment} rollout timed out in {cluster}").into());
    }
    Ok(())
}

/// Indent each line of a YAML string by `spaces` spaces.
fn indent_yaml(yaml: &str, spaces: usize) -> String {
    let prefix = " ".repeat(spaces);
    yaml.lines()
        .map(|l| {
            if l.is_empty() {
                String::new()
            } else {
                format!("{prefix}{l}")
            }
        })
        .collect::<Vec<_>>()
        .join("\n")
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    // -----------------------------------------------------------------------
    // Test utilities
    // -----------------------------------------------------------------------

    fn make_provider(site: &str, models: &[&str]) -> ProviderEndpoint {
        ProviderEndpoint {
            site: site.to_owned(),
            address: "10.0.0.1:30080".to_owned(),
            models: models.iter().map(|m| (*m).to_owned()).collect(),
            sni: format!("{site}.grid.internal"),
        }
    }

    // -----------------------------------------------------------------------
    // Config generation
    // -----------------------------------------------------------------------

    #[test]
    fn local_site_matches_consumer_site_arg() {
        let providers = vec![make_provider("site-a", &["model-x"])];
        let config = consumer_gateway_config("my-consumer", &providers);
        assert!(
            config.contains("local_site: my-consumer"),
            "local_site must match the consumer_site argument"
        );
    }

    #[test]
    fn static_candidates_include_all_provider_models() {
        let providers = vec![make_provider("site-a", &["model-1", "model-2"])];
        let config = consumer_gateway_config("consumer", &providers);
        assert!(
            config.contains("model-1"),
            "first model must appear in grid_route candidates"
        );
        assert!(
            config.contains("model-2"),
            "second model must appear in grid_route candidates"
        );
    }

    #[test]
    fn cluster_names_use_gateway_prefix() {
        let providers = vec![make_provider("site-a", &["model"])];
        let config = consumer_gateway_config("consumer", &providers);
        assert!(
            config.contains("gateway-site-a"),
            "load_balancer cluster name must use gateway-{{site}} convention"
        );
    }

    #[test]
    fn fallback_route_uses_first_provider_site() {
        let providers = vec![
            make_provider("site-a", &["model-a"]),
            make_provider("site-b", &["model-b"]),
        ];
        let config = consumer_gateway_config("consumer", &providers);
        assert!(
            config.contains("cluster: gateway-site-a"),
            "catch-all route must use first provider site as cluster"
        );
    }

    #[test]
    fn grid_route_and_load_balancer_filters_present() {
        let providers = vec![make_provider("site-a", &["model"])];
        let config = consumer_gateway_config("consumer", &providers);
        assert!(
            config.contains("filter: grid_route"),
            "grid_route filter must be present"
        );
        assert!(
            config.contains("filter: load_balancer"),
            "load_balancer filter must be present"
        );
    }

    #[test]
    fn multiple_providers_produce_multiple_candidates_and_clusters() {
        let providers = vec![
            make_provider("site-a", &["granite-3.3-8b"]),
            make_provider("site-b", &["llama-3.2-8b"]),
        ];
        let config = consumer_gateway_config("consumer", &providers);
        assert!(config.contains("granite-3.3-8b"), "site-a model must be a candidate");
        assert!(config.contains("llama-3.2-8b"), "site-b model must be a candidate");
        assert!(
            config.contains("gateway-site-a"),
            "site-a cluster must be in load_balancer"
        );
        assert!(
            config.contains("gateway-site-b"),
            "site-b cluster must be in load_balancer"
        );
    }

    #[test]
    fn candidate_cluster_matches_load_balancer_cluster() {
        let providers = vec![make_provider("site-a", &["model"])];
        let config = consumer_gateway_config("consumer", &providers);
        // Both grid_route candidate and load_balancer must use gateway-{site}
        let candidate_marker = "cluster: gateway-site-a";
        let cluster_marker = "- name: gateway-site-a";
        assert!(
            config.contains(candidate_marker),
            "grid_route candidate must reference gateway-site-a"
        );
        assert!(
            config.contains(cluster_marker),
            "load_balancer must define gateway-site-a"
        );
    }

    #[test]
    fn tls_paths_reference_cert_mount() {
        let providers = vec![make_provider("site-a", &["model"])];
        let config = consumer_gateway_config("consumer", &providers);
        assert!(
            config.contains(CERT_MOUNT_PATH),
            "load_balancer cluster TLS must reference the cert mount path"
        );
    }

    #[test]
    fn load_balancer_has_one_sni_per_provider() {
        let providers = vec![make_provider("site-a", &["model"])];
        let config = consumer_gateway_config("consumer", &providers);
        let sni_count = config.matches("sni: site-a.grid.internal").count();
        assert_eq!(sni_count, 1, "each provider cluster must emit one SNI entry");
    }
}
