//! Consumer gateway deployment and G2G routing verification.
//!
//! Deploys a consumer Praxis AI gateway into the first consumer-role cluster
//! defined in the environment config.  Two `grid_route` config modes are
//! supported:
//!
//! - **Static mode (default):** Generates candidates from provider site/model declarations in the environment config.
//! - **Overlay mode:** Reads a routing overlay `grid-config.json`. The overlay `local_site` and candidates drive
//!   `grid_route`; the `load_balancer` section is still generated from provider endpoints in the environment config.
//!
//! Provider endpoints are reached via `NodePort` over the kind Docker bridge.
//! Mutual TLS uses certificates generated by `xtask env up` and stored under
//! `tests/env/certs/`.

use std::{
    net::TcpStream,
    path::{Path, PathBuf},
    process::Command,
    time::{Duration, Instant},
};

use crate::env::{
    config::{ClusterDef, ClusterRole, EnvConfig},
    images::GATEWAY_IMAGE,
    kind::kubectl_context,
    kubectl,
    operator_overlay::{self, RoutingOverlay},
    verify::{HttpResponse, PortForwardGuard, Tally, find_free_port, parse_curl_output, safe_truncate, wait_for_port},
};

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/// Kubernetes namespace for consumer deployments.
const NAMESPACE: &str = "default";

/// Bearer token stored in the API-provider credential Secret for xtask validation.
///
/// This value is written to a Kubernetes Secret by the xtask validation harness
/// and then read back via the Secret-projection flow to build the Praxis consumer
/// config.  It is never logged, and the generated YAML receives the value from
/// the resolved Secret rather than embedding this compile-time constant directly.
///
/// The validation proves the Secret-backed CRD → Praxis-config flow, not
/// production credential management.
pub(crate) const API_PROVIDER_INJECTED_TOKEN: &str = "grid-api-fallback-secret";

/// Gateway HTTP port.
const GATEWAY_HTTP_PORT: u16 = 8080;

/// `NodePort` range minimum for provider gateway exposure.
const NODE_PORT_BASE: u16 = 30080;

/// Network probe timeout.
const PROBE_TIMEOUT: Duration = Duration::from_secs(5);

/// K8s Secret name holding TLS certs for the consumer gateway pod.
const TLS_SECRET_NAME: &str = "praxis-tls";

/// Path inside the consumer pod where TLS certs are mounted.
const CERT_MOUNT_PATH: &str = "/etc/praxis/tls";

/// Host-side cert directory (relative to workspace root).
const HOST_CERTS_DIR: &str = "tests/env/certs";

/// Base directory for mounted credential Secret files inside the consumer pod.
///
/// Each API credential Secret is mounted at `{CREDENTIAL_MOUNT_BASE}/{secret_name}/{key}`.
/// Token bytes never appear in Praxis `ConfigMap`s with this layout — the
/// `grid_credential_inject` filter reads from the mounted file path instead.
const CREDENTIAL_MOUNT_BASE: &str = "/run/secrets/grid-credentials";

// ---------------------------------------------------------------------------
// Network probe
// ---------------------------------------------------------------------------

/// Probe cross-kind network connectivity from the consumer cluster to all
/// provider gateways.
///
/// Outputs a PASS/FAIL/INFO report for each provider's node IP, `NodePort`
/// reachability, and Docker network adjacency.
///
/// # Errors
///
/// Returns an error only for fatal infrastructure failures.
pub(crate) fn probe_network(cfg: &EnvConfig) -> Result<(), Box<dyn std::error::Error>> {
    eprintln!("Probing cross-kind network connectivity...");
    eprintln!();

    let consumer_site = cfg
        .consumer_cluster_name()
        .ok_or("no consumer cluster configured in environment config")?;
    let consumer_ctx = kubectl_context(consumer_site);

    for name in &cfg.clusters.names {
        let Some(def) = cfg.clusters.definitions.get(name) else {
            continue;
        };
        if def.role != ClusterRole::Provider {
            continue;
        }
        probe_provider_reachability(name, def, &consumer_ctx)?;
    }

    Ok(())
}

/// Probe whether a provider cluster's gateway is reachable from the consumer.
#[expect(clippy::too_many_lines, reason = "sequential probe steps with diagnostic output")]
fn probe_provider_reachability(
    provider: &str,
    _def: &ClusterDef,
    consumer_ctx: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    let provider_ctx = kubectl_context(provider);

    let node_ip = get_kind_node_ip(&provider_ctx)?;
    eprintln!("  provider {provider} kind node IP: {node_ip}");

    let node_port = get_nodeport(&provider_ctx, "praxis-provider");
    match node_port {
        Some(port) => {
            eprintln!("  provider {provider} NodePort: {port}");
            let addr = format!("{node_ip}:{port}");
            let reachable = probe_tcp(&addr);
            if reachable {
                eprintln!("  [PASS] {provider} gateway {addr} reachable from host");
            } else {
                eprintln!(
                    "  [INFO] {provider} gateway {addr} not reachable from host \
                     (may still work from inside cluster)"
                );
            }
        },
        None => {
            eprintln!(
                "  [INFO] {provider} gateway has no NodePort; \
                 will use port-forward from consumer"
            );
        },
    }

    let same_network = check_docker_network(&provider_ctx, consumer_ctx)?;
    if same_network {
        eprintln!("  [PASS] provider and consumer kind nodes share a Docker network");
    } else {
        eprintln!("  [WARN] provider and consumer kind nodes may be on different Docker networks");
        eprintln!("         Cross-cluster routing may require NodePort exposure and host-level access");
    }

    println!();
    Ok(())
}

/// Get the Docker IP of the first kind node in a cluster.
fn get_kind_node_ip(context: &str) -> Result<String, Box<dyn std::error::Error>> {
    let output = Command::new("kubectl")
        .args([
            "--context",
            context,
            "get",
            "nodes",
            "-o",
            "jsonpath={.items[0].status.addresses[?(@.type==\"InternalIP\")].address}",
        ])
        .output()?;
    let ip = String::from_utf8(output.stdout)?.trim().to_owned();
    if ip.is_empty() {
        return Err(format!("could not get node IP for context {context}").into());
    }
    Ok(ip)
}

/// Get the `NodePort` for a service if it is exposed as `NodePort`.
fn get_nodeport(context: &str, service: &str) -> Option<u16> {
    let output = Command::new("kubectl")
        .args([
            "--context",
            context,
            "get",
            "service",
            service,
            "-n",
            NAMESPACE,
            "-o",
            "jsonpath={.spec.ports[0].nodePort}",
        ])
        .output()
        .ok()?;
    let port_str = String::from_utf8(output.stdout).ok()?;
    port_str.trim().parse().ok().filter(|&p: &u16| p > 0)
}

/// Probe a TCP address.
#[expect(
    clippy::disallowed_methods,
    reason = "synchronous networking probe; no async runtime available"
)]
fn probe_tcp(addr: &str) -> bool {
    let deadline = Instant::now() + PROBE_TIMEOUT;
    loop {
        if TcpStream::connect(addr).is_ok() {
            return true;
        }
        if Instant::now() >= deadline {
            return false;
        }
        std::thread::sleep(Duration::from_millis(500));
    }
}

/// Check whether provider and consumer kind nodes share a Docker network.
fn check_docker_network(provider_ctx: &str, consumer_ctx: &str) -> Result<bool, Box<dyn std::error::Error>> {
    let provider_node = get_node_name(provider_ctx)?;
    let consumer_node = get_node_name(consumer_ctx)?;
    let provider_nets = get_docker_networks(&provider_node);
    let consumer_nets = get_docker_networks(&consumer_node);
    Ok(provider_nets.iter().any(|n| consumer_nets.contains(n)))
}

/// Get the first node name in a cluster.
fn get_node_name(context: &str) -> Result<String, Box<dyn std::error::Error>> {
    let output = Command::new("kubectl")
        .args([
            "--context",
            context,
            "get",
            "nodes",
            "-o",
            "jsonpath={.items[0].metadata.name}",
        ])
        .output()?;
    Ok(String::from_utf8(output.stdout)?.trim().to_owned())
}

/// Get Docker network names for a container (kind node).
fn get_docker_networks(container: &str) -> Vec<String> {
    Command::new("docker")
        .args([
            "inspect",
            "--format",
            "{{range $k,$v := .NetworkSettings.Networks}}{{$k}}\n{{end}}",
            container,
        ])
        .output()
        .ok()
        .and_then(|o| String::from_utf8(o.stdout).ok())
        .unwrap_or_default()
        .lines()
        .map(str::to_owned)
        .collect()
}

// ---------------------------------------------------------------------------
// Consumer gateway deployment
// ---------------------------------------------------------------------------

/// Deploy the consumer gateway.
///
/// Resolves the consumer cluster from the environment config, collects
/// provider `NodePort` endpoints, creates the TLS secret from locally
/// generated certificates, applies a `grid_route` `ConfigMap`, and
/// deploys the Praxis AI gateway Deployment and Service.
///
/// When `overlay_config` is `Some(path)`, reads the routing overlay
/// `grid-config.json` at that path. The overlay `local_site` and candidates
/// drive the `grid_route` stanza; the `load_balancer` section is still
/// generated from provider endpoints in the environment config.
///
/// When `overlay_config` is `None`, the static config derived from provider
/// site/model declarations is used (existing behaviour).
///
/// # Errors
///
/// Returns an error if the consumer cluster is not configured, the overlay
/// file is invalid, no provider gateway endpoints are found, or any
/// Kubernetes apply fails.
pub(crate) fn deploy_consumer(
    cfg: &EnvConfig,
    overlay_config: Option<&Path>,
) -> Result<(), Box<dyn std::error::Error>> {
    let consumer_site = cfg
        .consumer_cluster_name()
        .ok_or("no consumer cluster configured in environment config")?;
    let consumer_ctx = kubectl_context(consumer_site);
    eprintln!("  deploying consumer gateway to {consumer_ctx}...");

    let overlay = overlay_config.map(read_overlay_file).transpose()?;

    let provider_endpoints = collect_provider_endpoints(cfg)?;
    if provider_endpoints.is_empty() {
        return Err("no provider gateway endpoints found".into());
    }

    // When an overlay is provided, filter out candidates whose site has no
    // matching local provider.  This handles overlays produced by the Grid
    // operator that may include remote/API-provider candidates (e.g. external
    // API providers) that cannot be routed through the local kind environment.
    // At least one routeable candidate must remain after filtering.
    let filtered_overlay = if let Some(o) = &overlay {
        Some(filter_overlay_for_local_providers(o, &provider_endpoints)?)
    } else {
        None
    };

    create_consumer_tls_secret(&consumer_ctx, consumer_site)?;
    apply_consumer_config(
        &consumer_ctx,
        consumer_site,
        &provider_endpoints,
        filtered_overlay.as_ref().or(overlay.as_ref()),
    )?;
    apply_consumer_deployment(&consumer_ctx)?;
    rollout_restart(&consumer_ctx, "praxis-consumer")?;

    kubectl::wait_for_rollout(&consumer_ctx, "praxis-consumer", consumer_site)?;

    eprintln!("  [PASS] consumer gateway ready in {consumer_ctx}");
    Ok(())
}

/// Read and parse a routing overlay JSON file.
///
/// # Errors
///
/// Returns an error if the file cannot be read or the JSON is invalid.
fn read_overlay_file(path: &Path) -> Result<RoutingOverlay, Box<dyn std::error::Error>> {
    let json =
        std::fs::read_to_string(path).map_err(|e| format!("could not read overlay file {}: {e}", path.display()))?;
    Ok(operator_overlay::parse_grid_config_json(&json)?)
}

/// Filter an operator-generated overlay to only candidates routable locally.
///
/// Retains candidates whose `site` field matches a configured provider site.
/// Candidates referencing remote or external-API sites (e.g. sites only
/// reachable via SWIM discovery or external network) are logged and dropped.
///
/// # Errors
///
/// Returns an error when all candidates are filtered out — no locally-routable
/// route would remain, making the consumer gateway deployment useless.
#[expect(
    clippy::too_many_lines,
    reason = "per-candidate filtering loop with diagnostic output for each excluded candidate"
)]
fn filter_overlay_for_local_providers(
    overlay: &RoutingOverlay,
    providers: &[ProviderEndpoint],
) -> Result<RoutingOverlay, Box<dyn std::error::Error>> {
    let known_sites: Vec<&str> = providers.iter().map(|p| p.site.as_str()).collect();
    let mut kept = Vec::new();
    for c in &overlay.candidates {
        // Accept the candidate when either the `site` field or the `cluster` field matches a
        // known local provider.  The `cluster` field (derived from `routingClusterRef`) is the
        // stable routing identity; `site` may differ when auto-discovered `GridSite` resources
        // are present, causing the overlay renderer to use the `GridSite` name as the site field
        // instead of `routingClusterRef`.
        if known_sites.contains(&c.site.as_str()) || known_sites.contains(&c.cluster.as_str()) {
            kept.push(c.clone());
        } else {
            eprintln!(
                "  [INFO] overlay candidate model=\"{}\" site=\"{}\" cluster=\"{}\" \
                 has no local provider endpoint (known: [{}]); excluded from consumer gateway config",
                c.name,
                c.site,
                c.cluster,
                known_sites.join(", ")
            );
        }
    }
    if kept.is_empty() {
        return Err(format!(
            "no overlay candidates have a matching local provider endpoint; \
             known provider sites: [{}]; \
             hint: set spec.routingClusterRef on InferenceProvider resources \
             to match a local provider site name",
            known_sites.join(", ")
        )
        .into());
    }
    Ok(RoutingOverlay {
        network: overlay.network.clone(),
        local_site: overlay.local_site.clone(),
        candidates: kept,
    })
}

/// Verify that every overlay candidate site has a matching provider endpoint.
///
/// The `load_balancer` section uses `gateway-{provider.site}` as cluster
/// names.  The `grid_route` candidates use `gateway-{candidate.site}`.  For
/// Praxis to route successfully, both sides must reference the same sites.
///
/// This function is used in unit tests to validate individual candidate
/// sets.  Production deployment uses [`filter_overlay_for_local_providers`]
/// instead, which skips un-routable candidates rather than failing.
///
/// # Errors
///
/// Returns an error if any `candidate.site` is absent from the provider list,
/// including the model name, the unknown site, and the known provider sites.
#[cfg(test)]
fn validate_overlay_sites_supported(
    overlay: &RoutingOverlay,
    providers: &[ProviderEndpoint],
) -> Result<(), Box<dyn std::error::Error>> {
    let known_sites: Vec<&str> = providers.iter().map(|p| p.site.as_str()).collect();
    for c in &overlay.candidates {
        if !known_sites.contains(&c.site.as_str()) {
            return Err(format!(
                "overlay candidate model=\"{}\" site=\"{}\" cluster=\"{}\" \
                 has no matching local provider endpoint\n\
                 known provider sites: [{}]\n\
                 hint: set spec.routingClusterRef on the InferenceProvider \
                 to a site name from the environment config",
                c.name,
                c.site,
                c.cluster,
                known_sites.join(", ")
            )
            .into());
        }
    }
    Ok(())
}

/// Collect provider gateway endpoints for consumer routing.
///
/// Tries to get `NodePort` addresses for each provider cluster.
/// If no `NodePort` exists, exposes one.
fn collect_provider_endpoints(cfg: &EnvConfig) -> Result<Vec<ProviderEndpoint>, Box<dyn std::error::Error>> {
    let mut endpoints = Vec::new();
    for name in &cfg.clusters.names {
        let Some(def) = cfg.clusters.definitions.get(name) else {
            continue;
        };
        if def.role != ClusterRole::Provider || def.models.is_empty() {
            continue;
        }
        endpoints.push(resolve_provider_endpoint(name, def)?);
    }
    for ep in &endpoints {
        eprintln!(
            "  provider endpoint: {} @ {} (models: {})",
            ep.site,
            ep.address,
            ep.models.join(", ")
        );
    }
    Ok(endpoints)
}

/// Resolve the reachable endpoint for one provider cluster.
fn resolve_provider_endpoint(name: &str, def: &ClusterDef) -> Result<ProviderEndpoint, Box<dyn std::error::Error>> {
    let ctx = kubectl_context(name);
    let node_port = if let Some(p) = get_nodeport(&ctx, "praxis-provider") {
        p
    } else {
        eprintln!("  [WARN] no NodePort for {name}; exposing via NodePort now...");
        expose_gateway_nodeport(&ctx, name)?;
        get_nodeport(&ctx, "praxis-provider").unwrap_or(NODE_PORT_BASE)
    };
    let node_ip = get_kind_node_ip(&ctx).unwrap_or_else(|_| "127.0.0.1".to_owned());
    Ok(ProviderEndpoint {
        site: name.to_owned(),
        address: format!("{node_ip}:{node_port}"),
        models: def.models.clone(),
        sni: format!("{name}.grid.internal"),
    })
}

/// Expose a provider gateway as `NodePort` if not already exposed.
fn expose_gateway_nodeport(context: &str, site: &str) -> Result<(), Box<dyn std::error::Error>> {
    let status = Command::new("kubectl")
        .args([
            "--context",
            context,
            "-n",
            NAMESPACE,
            "patch",
            "service",
            "praxis-provider",
            "-p",
            &format!(
                r#"{{"spec":{{"type":"NodePort","ports":[{{"port":{GATEWAY_HTTP_PORT},"targetPort":{GATEWAY_HTTP_PORT},"nodePort":{NODE_PORT_BASE}}}]}}}}"#
            ),
        ])
        .status()?;
    if !status.success() {
        return Err(format!("failed to patch praxis-provider service in {site}").into());
    }
    Ok(())
}

/// Provider endpoint resolved for consumer routing.
struct ProviderEndpoint {
    /// Site name (matches the provider cluster name).
    site: String,
    /// Reachable `host:port` address for the provider gateway.
    address: String,
    /// Configured model names for this provider.
    models: Vec<String>,
    /// TLS SNI hostname (used in future mTLS extensions).
    #[expect(dead_code, reason = "future mTLS extension point")]
    sni: String,
}

/// Create (or update) the TLS secret in the consumer cluster.
///
/// Loads the locally-generated certificate for `consumer_site`, its private
/// key, and the local CA certificate from `tests/env/certs/`.  These are
/// created by `xtask env up`.
fn create_consumer_tls_secret(context: &str, consumer_site: &str) -> Result<(), Box<dyn std::error::Error>> {
    let certs_dir = PathBuf::from(HOST_CERTS_DIR);
    let cert = certs_dir.join(format!("{consumer_site}-cert.pem"));
    let key = certs_dir.join(format!("{consumer_site}-key.pem"));
    let ca = certs_dir.join("ca.pem");

    eprintln!("  creating TLS secret in {context}...");

    let output = Command::new("kubectl")
        .args([
            "create",
            "secret",
            "generic",
            TLS_SECRET_NAME,
            &format!("--from-file=tls.crt={}", cert.display()),
            &format!("--from-file=tls.key={}", key.display()),
            &format!("--from-file=ca.crt={}", ca.display()),
            "--namespace",
            NAMESPACE,
            "--dry-run=client",
            "-o",
            "yaml",
        ])
        .output()?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(format!("kubectl create secret failed: {stderr}").into());
    }

    let yaml = String::from_utf8(output.stdout)?;
    kubectl::apply_manifest(context, &yaml)
}

/// Apply the consumer gateway `ConfigMap`.
///
/// When `overlay` is `Some`, uses overlay candidates and `local_site`.
/// When `overlay` is `None`, uses static config from `consumer_site` and `providers`.
fn apply_consumer_config(
    context: &str,
    consumer_site: &str,
    providers: &[ProviderEndpoint],
    overlay: Option<&RoutingOverlay>,
) -> Result<(), Box<dyn std::error::Error>> {
    let config = consumer_gateway_config(consumer_site, providers, overlay);
    let yaml = format!(
        "apiVersion: v1\n\
         kind: ConfigMap\n\
         metadata:\n\
         \x20 name: praxis-consumer-config\n\
         \x20 namespace: {NAMESPACE}\n\
         data:\n\
         \x20 praxis.yaml: |\n\
         {}\n",
        indent_yaml(&config, 4)
    );
    kubectl::apply_manifest(context, &yaml)
}

/// Build the consumer Praxis config YAML.
///
/// When `overlay` is `Some`, candidates are taken from the overlay;
/// the `load_balancer` section is still generated from `providers` so that
/// mTLS endpoint config is preserved.
///
/// When `overlay` is `None`, generates a static `grid_route` stanza from
/// `providers` (one candidate per model per site).
///
/// `grid_route.local_site` is always `consumer_site` — the consumer's own
/// cluster identity.  The overlay's `local_site` field identifies the
/// `GridNetwork`, not the consumer site, and must not be used here.
///
/// A `load_balancer` section provides mTLS cluster definitions for each
/// provider.  A catch-all `router` route falls through to the first provider
/// cluster for requests without a recognised model header.
///
/// The `grid_route` cluster convention is `gateway-{site}`, which must match
/// the names produced by [`build_clusters`].
#[expect(clippy::too_many_lines, reason = "Praxis config YAML generation")]
fn consumer_gateway_config(
    consumer_site: &str,
    providers: &[ProviderEndpoint],
    overlay: Option<&RoutingOverlay>,
) -> String {
    let candidates = if let Some(o) = overlay {
        operator_overlay::candidates_yaml(o)
    } else {
        build_grid_route_candidates(providers)
    };
    let local_site = consumer_site;
    let clusters = build_clusters(providers);
    format!(
        "listeners:\n\
         \x20 - name: public\n\
         \x20   address: \"0.0.0.0:{GATEWAY_HTTP_PORT}\"\n\
         \x20   filter_chains:\n\
         \x20     - consumer-chain\n\
         filter_chains:\n\
         \x20 - name: consumer-chain\n\
         \x20   filters:\n\
         \x20     - filter: json_body_field\n\
         \x20       field: model\n\
         \x20       header: X-Model\n\
         \x20     - filter: grid_route\n\
         \x20       local_site: {local_site}\n\
         \x20       model_header: X-Model\n\
         \x20       candidates:\n\
         {candidates}\n\
         \x20     - filter: load_balancer\n\
         \x20       clusters:\n\
         {clusters}\n\
         admin:\n\
         \x20 address: \"127.0.0.1:9901\"\n\
         shutdown_timeout_secs: 5\n"
    )
}

/// Build `grid_route` candidate entries from provider endpoints.
///
/// Each `(model, site)` pair becomes one `inference_model` candidate.
/// The cluster name is `gateway-{site}`, matching the `load_balancer` section.
fn build_grid_route_candidates(providers: &[ProviderEndpoint]) -> String {
    providers
        .iter()
        .flat_map(|ep| {
            ep.models.iter().map(move |m| {
                format!(
                    "\x20\x20\x20\x20\x20\x20\x20\x20 - kind: inference_model\n\
                     \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20 name: {m}\n\
                     \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20 site: {}\n\
                     \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20 cluster: gateway-{}",
                    ep.site, ep.site
                )
            })
        })
        .collect::<Vec<_>>()
        .join("\n")
}

/// Build `load_balancer` cluster entries for each provider.
///
/// Each cluster uses mTLS: the consumer presents its locally-generated client
/// certificate, and verifies the provider server certificate against the
/// locally-generated CA.  SNI is set to `{site}.grid.internal` which must
/// match the Subject Alternative Name in the provider's server certificate.
fn build_clusters(providers: &[ProviderEndpoint]) -> String {
    providers
        .iter()
        .map(|ep| {
            [
                format!("         - name: gateway-{}", ep.site),
                "           tls:".to_owned(),
                "             ca:".to_owned(),
                format!("               ca_path: {CERT_MOUNT_PATH}/ca.crt"),
                "             client_cert:".to_owned(),
                format!("               cert_path: {CERT_MOUNT_PATH}/tls.crt"),
                format!("               key_path: {CERT_MOUNT_PATH}/tls.key"),
                format!("             sni: {}.grid.internal", ep.site),
                "             verify: true".to_owned(),
                "           endpoints:".to_owned(),
                format!("             - \"{}\"", ep.address),
            ]
            .join("\n")
        })
        .collect::<Vec<_>>()
        .join("\n")
}

/// Apply the consumer gateway Deployment and Service.
#[expect(clippy::too_many_lines, reason = "K8s manifest generation")]
fn apply_consumer_deployment(context: &str) -> Result<(), Box<dyn std::error::Error>> {
    let yaml = format!(
        "apiVersion: apps/v1\n\
         kind: Deployment\n\
         metadata:\n\
         \x20 name: praxis-consumer\n\
         \x20 namespace: {NAMESPACE}\n\
         spec:\n\
         \x20 replicas: 1\n\
         \x20 selector:\n\
         \x20   matchLabels:\n\
         \x20     app: praxis-consumer\n\
         \x20 template:\n\
         \x20   metadata:\n\
         \x20     labels:\n\
         \x20       app: praxis-consumer\n\
         \x20   spec:\n\
         \x20     containers:\n\
         \x20       - name: praxis-ai\n\
         \x20         image: {GATEWAY_IMAGE}\n\
         \x20         imagePullPolicy: Never\n\
         \x20         ports:\n\
         \x20           - containerPort: {GATEWAY_HTTP_PORT}\n\
         \x20         args:\n\
         \x20           - \"--config\"\n\
         \x20           - \"/etc/praxis/praxis.yaml\"\n\
         \x20         volumeMounts:\n\
         \x20           - name: config\n\
         \x20             mountPath: /etc/praxis\n\
         \x20             readOnly: true\n\
         \x20           - name: tls-certs\n\
         \x20             mountPath: {CERT_MOUNT_PATH}\n\
         \x20             readOnly: true\n\
         \x20     volumes:\n\
         \x20       - name: config\n\
         \x20         configMap:\n\
         \x20           name: praxis-consumer-config\n\
         \x20       - name: tls-certs\n\
         \x20         secret:\n\
         \x20           secretName: {TLS_SECRET_NAME}\n\
         ---\n\
         apiVersion: v1\n\
         kind: Service\n\
         metadata:\n\
         \x20 name: praxis-consumer\n\
         \x20 namespace: {NAMESPACE}\n\
         spec:\n\
         \x20 selector:\n\
         \x20   app: praxis-consumer\n\
         \x20 ports:\n\
         \x20   - port: {GATEWAY_HTTP_PORT}\n\
         \x20     targetPort: {GATEWAY_HTTP_PORT}\n"
    );
    kubectl::apply_manifest(context, &yaml)
}

/// Deploy the consumer gateway with an additional Secret volume mount.
///
/// Extends [`apply_consumer_deployment`] with a `volumes` / `volumeMounts`
/// entry that makes the credential Secret available at
/// `{CREDENTIAL_MOUNT_BASE}/{secret_name}/{secret_key}` inside the pod.
///
/// This allows `grid_credential_inject` to use `file:` as its token source
/// rather than an inline `value:`, keeping token bytes out of `ConfigMap`s.
#[expect(
    clippy::too_many_lines,
    reason = "Deployment + Service YAML with two volumes; mirrors apply_consumer_deployment"
)]
fn apply_consumer_deployment_with_credential_mount(
    context: &str,
    secret_name: &str,
    secret_key: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    let mount_path = format!("{CREDENTIAL_MOUNT_BASE}/{secret_name}");
    let yaml = format!(
        "apiVersion: apps/v1\n\
         kind: Deployment\n\
         metadata:\n\
         \x20 name: praxis-consumer\n\
         \x20 namespace: {NAMESPACE}\n\
         spec:\n\
         \x20 replicas: 1\n\
         \x20 selector:\n\
         \x20   matchLabels:\n\
         \x20     app: praxis-consumer\n\
         \x20 template:\n\
         \x20   metadata:\n\
         \x20     labels:\n\
         \x20       app: praxis-consumer\n\
         \x20   spec:\n\
         \x20     containers:\n\
         \x20       - name: praxis-ai\n\
         \x20         image: {GATEWAY_IMAGE}\n\
         \x20         imagePullPolicy: Never\n\
         \x20         ports:\n\
         \x20           - containerPort: {GATEWAY_HTTP_PORT}\n\
         \x20         args:\n\
         \x20           - \"--config\"\n\
         \x20           - \"/etc/praxis/praxis.yaml\"\n\
         \x20         volumeMounts:\n\
         \x20           - name: config\n\
         \x20             mountPath: /etc/praxis\n\
         \x20             readOnly: true\n\
         \x20           - name: tls-certs\n\
         \x20             mountPath: {CERT_MOUNT_PATH}\n\
         \x20             readOnly: true\n\
         \x20           - name: api-creds\n\
         \x20             mountPath: {mount_path}\n\
         \x20             readOnly: true\n\
         \x20     volumes:\n\
         \x20       - name: config\n\
         \x20         configMap:\n\
         \x20           name: praxis-consumer-config\n\
         \x20       - name: tls-certs\n\
         \x20         secret:\n\
         \x20           secretName: {TLS_SECRET_NAME}\n\
         \x20       - name: api-creds\n\
         \x20         secret:\n\
         \x20           secretName: {secret_name}\n\
         \x20           items:\n\
         \x20             - key: {secret_key}\n\
         \x20               path: {secret_key}\n\
         ---\n\
         apiVersion: v1\n\
         kind: Service\n\
         metadata:\n\
         \x20 name: praxis-consumer\n\
         \x20 namespace: {NAMESPACE}\n\
         spec:\n\
         \x20 selector:\n\
         \x20   app: praxis-consumer\n\
         \x20 ports:\n\
         \x20   - port: {GATEWAY_HTTP_PORT}\n\
         \x20     targetPort: {GATEWAY_HTTP_PORT}\n"
    );
    kubectl::apply_manifest(context, &yaml)
}

// ---------------------------------------------------------------------------
// API provider fallback consumer deployment
// ---------------------------------------------------------------------------

/// Build the Praxis consumer config for the API-provider fallback validation.
///
/// Generates a `grid_route` section from the overlay (which must include both
/// the local provider and the `api_provider` candidate), and a `load_balancer`
/// section with:
///
/// - mTLS clusters for each local provider (identical to the standard path).
/// - A **plain-HTTP** cluster for `gateway-{api_cluster}` pointing to the in-cluster mock API-provider service.  No TLS
///   is used for this cluster because the mock represents a direct API endpoint, not a Grid provider gateway.  In
///   production the gateway would reach the provider over HTTPS using credentials managed by the operator; the kind
///   mock uses HTTP for simplicity.
///
/// The caller passes the raw overlay (all candidates intact — no
/// `filter_overlay_for_local_providers` is applied) so that the API-provider
/// candidate survives into the `grid_route` stanza.
///
/// Credential injection here is gateway-config-level proof using Praxis
/// `headers` / `request_set`. It does not prove the future operator path that
/// reads an `InferenceProvider` Secret reference and manages credential rotation.
///
/// **Caveat:** the bearer token is necessarily present in the generated Praxis
/// consumer `ConfigMap` (`praxis-consumer-config`).  For the xtask validation
/// harness this is acceptable; production deployments should use mounted Secret
/// volumes or a native Praxis secret-reference mechanism.
#[expect(
    clippy::too_many_lines,
    reason = "Praxis YAML generation with mTLS and plain-HTTP clusters"
)]
#[expect(
    clippy::too_many_arguments,
    reason = "six distinct config parameters: site, providers, overlay, cluster name, endpoint, token"
)]
fn build_api_fallback_consumer_config(
    consumer_site: &str,
    local_providers: &[ProviderEndpoint],
    overlay: &RoutingOverlay,
    api_cluster_name: &str,
    api_provider_endpoint: &str,
    api_provider_token: &str,
) -> String {
    let candidates = operator_overlay::candidates_yaml(overlay);
    let local_site = consumer_site;
    let mtls_clusters = build_clusters(local_providers);
    let api_cluster_yaml = format!(
        r#"         - name: gateway-{api_cluster_name}
           endpoints:
             - "{api_provider_endpoint}""#
    );

    format!(
        r#"listeners:
  - name: public
    address: "0.0.0.0:{GATEWAY_HTTP_PORT}"
    filter_chains:
      - consumer-chain
filter_chains:
  - name: consumer-chain
    filters:
      - filter: json_body_field
        field: model
        header: X-Model
      - filter: grid_route
        local_site: {local_site}
        model_header: X-Model
        candidates:
{candidates}
      - filter: headers
        request_set:
          - name: "Authorization"
            value: "Bearer {api_provider_token}"
      - filter: load_balancer
        clusters:
{mtls_clusters}
{api_cluster_yaml}
admin:
  address: "127.0.0.1:9901"
shutdown_timeout_secs: 5
"#
    )
}

/// Build the consumer Praxis config for API-provider fallback routing — native injection mode.
///
/// Unlike [`build_api_fallback_consumer_config`] which embeds the bearer token as a
/// static string inside `filter: headers` / `request_set`, this native variant:
///
/// - Emits credential `secretRef` data in the `grid_route` candidates block via
///   [`operator_overlay::candidates_yaml_with_credentials`].
/// - Uses `filter: grid_credential_inject` with a `file:` source pointing at the mounted Kubernetes Secret file — token
///   bytes never appear in the `ConfigMap`.
///
/// **Token placement:** the bearer token is read by `grid_credential_inject` from
/// the file at `{CREDENTIAL_MOUNT_BASE}/{secret_name}/{secret_key}` inside the pod.
/// **The token does not appear in this `ConfigMap`**, in the operator overlay JSON,
/// or in the `grid_route` candidates block.
#[expect(
    clippy::too_many_lines,
    reason = "Praxis YAML generation with mTLS + plain-HTTP clusters and native credential inject"
)]
#[expect(
    clippy::too_many_arguments,
    reason = "distinct argument per secretRef field — collapsing would obscure the security boundary"
)]
fn build_api_fallback_consumer_config_native(
    consumer_site: &str,
    local_providers: &[ProviderEndpoint],
    overlay: &RoutingOverlay,
    api_cluster_name: &str,
    api_provider_endpoint: &str,
    secret_name: &str,
    secret_namespace: &str,
    secret_key: &str,
) -> String {
    let candidates = operator_overlay::candidates_yaml_with_credentials(overlay);
    let local_site = consumer_site;
    let mtls_clusters = build_clusters(local_providers);
    let api_cluster_yaml = format!(
        r#"         - name: gateway-{api_cluster_name}
           endpoints:
             - "{api_provider_endpoint}""#
    );
    // Token read from mounted file — never embedded in this YAML.
    let token_file_path = format!("{CREDENTIAL_MOUNT_BASE}/{secret_name}/{secret_key}");

    format!(
        r#"listeners:
  - name: public
    address: "0.0.0.0:{GATEWAY_HTTP_PORT}"
    filter_chains:
      - consumer-chain
filter_chains:
  - name: consumer-chain
    filters:
      - filter: json_body_field
        field: model
        header: X-Model
      - filter: grid_route
        local_site: {local_site}
        model_header: X-Model
        candidates:
{candidates}
      - filter: grid_credential_inject
        credentials:
          - name: {secret_name}
            namespace: {secret_namespace}
            key: {secret_key}
            strategy: bearer_token
            file: {token_file_path}
      - filter: load_balancer
        clusters:
{mtls_clusters}
{api_cluster_yaml}
admin:
  address: "127.0.0.1:9901"
shutdown_timeout_secs: 5
"#
    )
}

/// Deploy the consumer gateway configured for API-provider fallback — native injection mode.
///
/// Uses [`build_api_fallback_consumer_config_native`] which emits credential secretRef
/// in the `grid_route` candidates block and uses `filter: grid_credential_inject`
/// with a `file:` source.
///
/// **Token placement:** the bearer token is read from a mounted Kubernetes Secret
/// file at `{CREDENTIAL_MOUNT_BASE}/{secret_name}/{secret_key}` inside the pod.
/// The token does **not** appear in the consumer Praxis `ConfigMap`, in the
/// operator overlay JSON, or in the `grid_route` candidates block.
#[expect(
    clippy::too_many_lines,
    reason = "sequential deploy steps: tls secret, config, deployment with credential mount, rollout"
)]
#[expect(
    clippy::too_many_arguments,
    reason = "distinct argument per secretRef field — collapsing would obscure the security boundary"
)]
pub(crate) fn deploy_consumer_for_api_fallback_native(
    cfg: &EnvConfig,
    overlay: &RoutingOverlay,
    api_cluster_name: &str,
    api_provider_endpoint: &str,
    secret_name: &str,
    secret_namespace: &str,
    secret_key: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    let consumer_site = cfg
        .consumer_cluster_name()
        .ok_or("no consumer cluster configured in environment config")?;
    let consumer_ctx = kubectl_context(consumer_site);
    eprintln!("  deploying native-credential consumer gateway to {consumer_ctx}...");

    let provider_endpoints = collect_provider_endpoints(cfg)?;
    if provider_endpoints.is_empty() {
        return Err("no provider gateway endpoints found in config".into());
    }

    let config = build_api_fallback_consumer_config_native(
        consumer_site,
        &provider_endpoints,
        overlay,
        api_cluster_name,
        api_provider_endpoint,
        secret_name,
        secret_namespace,
        secret_key,
    );

    create_consumer_tls_secret(&consumer_ctx, consumer_site)?;

    let yaml = format!(
        "apiVersion: v1\n\
         kind: ConfigMap\n\
         metadata:\n\
         \x20 name: praxis-consumer-config\n\
         \x20 namespace: {NAMESPACE}\n\
         data:\n\
         \x20 praxis.yaml: |\n\
         {}\n",
        indent_yaml(&config, 4)
    );
    kubectl::apply_manifest(&consumer_ctx, &yaml)?;

    // Mount the credential Secret as a file — the token never touches the ConfigMap.
    apply_consumer_deployment_with_credential_mount(&consumer_ctx, secret_name, secret_key)?;
    rollout_restart(&consumer_ctx, "praxis-consumer")?;
    kubectl::wait_for_rollout(&consumer_ctx, "praxis-consumer", consumer_site)?;

    eprintln!("  [PASS] native-credential consumer gateway ready in {consumer_ctx}");
    Ok(())
}

/// Deploy the consumer gateway configured for API-provider fallback routing.
///
/// Unlike [`deploy_consumer`], this function does **not** filter the overlay for
/// local providers — the API-provider candidate must survive into the generated
/// Praxis config.  The `api_provider_endpoint` is the in-cluster address of the
/// mock API-provider service (e.g. `mock-api-provider.default.svc:8080`).
#[expect(
    clippy::too_many_lines,
    reason = "sequential deploy steps: secret, config, deployment, rollout"
)]
pub(crate) fn deploy_consumer_for_api_fallback(
    cfg: &EnvConfig,
    overlay: &RoutingOverlay,
    api_cluster_name: &str,
    api_provider_endpoint: &str,
    api_provider_token: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    let consumer_site = cfg
        .consumer_cluster_name()
        .ok_or("no consumer cluster configured in environment config")?;
    let consumer_ctx = kubectl_context(consumer_site);
    eprintln!("  deploying api-fallback consumer gateway to {consumer_ctx}...");

    let provider_endpoints = collect_provider_endpoints(cfg)?;
    if provider_endpoints.is_empty() {
        return Err("no provider gateway endpoints found in config".into());
    }

    let config = build_api_fallback_consumer_config(
        consumer_site,
        &provider_endpoints,
        overlay,
        api_cluster_name,
        api_provider_endpoint,
        api_provider_token,
    );

    create_consumer_tls_secret(&consumer_ctx, consumer_site)?;

    let yaml = format!(
        "apiVersion: v1\n\
         kind: ConfigMap\n\
         metadata:\n\
         \x20 name: praxis-consumer-config\n\
         \x20 namespace: {NAMESPACE}\n\
         data:\n\
         \x20 praxis.yaml: |\n\
         {}\n",
        indent_yaml(&config, 4)
    );
    kubectl::apply_manifest(&consumer_ctx, &yaml)?;

    apply_consumer_deployment(&consumer_ctx)?;
    rollout_restart(&consumer_ctx, "praxis-consumer")?;
    kubectl::wait_for_rollout(&consumer_ctx, "praxis-consumer", consumer_site)?;

    eprintln!("  [PASS] api-fallback consumer gateway ready in {consumer_ctx}");
    Ok(())
}

// ---------------------------------------------------------------------------
// Full-grid consumer deployment and verification
// ---------------------------------------------------------------------------

/// Build the consumer Praxis config for the full-grid routing validation.
///
/// Generates a config with:
/// - mTLS clusters for each local provider site (site-east, site-west)
/// - A plain-HTTP cluster for the cloud-managed mock
/// - A plain-HTTP cluster for the API-provider mock
/// - `filter: headers` / `request_set` injecting the provider credential
///
/// All four backend clusters are included so the `grid_route` candidates from
/// the operator overlay can be routed without filtering.
///
/// The cloud/API clusters are local OpenAI-compatible mocks. They validate Grid
/// backend-kind routing and scoring categories, not provider-specific protocols
/// such as `SigV4`, `OAuth2`, or real external API calls.
///
/// API credentials are injected with Praxis `headers` / `request_set` for the
/// validation.  **Caveat:** the bearer token is necessarily present in the
/// generated Praxis consumer `ConfigMap` (`praxis-consumer-config`).  For the
/// xtask validation harness this is acceptable; production deployments should
/// move to mounted Secret volumes or a native Praxis secret-reference
/// mechanism when available rather than embedding credentials in a `ConfigMap`.
#[expect(clippy::too_many_lines, reason = "Praxis YAML generation for all four cluster types")]
#[expect(
    clippy::too_many_arguments,
    reason = "distinct argument per backend kind — grouping would obscure the intended topology"
)]
fn build_full_grid_consumer_config(
    consumer_site: &str,
    mtls_providers: &[ProviderEndpoint],
    overlay: &RoutingOverlay,
    cloud_cluster_name: &str,
    cloud_endpoint: &str,
    api_cluster_name: &str,
    api_endpoint: &str,
    api_provider_token: &str,
) -> String {
    let candidates = operator_overlay::candidates_yaml(overlay);
    let local_site = consumer_site;
    let mtls_clusters = build_clusters(mtls_providers);
    // Plain-HTTP clusters for cloud-managed and api-provider mocks.
    // Cloud APIs use HTTPS in production; the kind mocks use plain HTTP for simplicity.
    let cloud_cluster_yaml = format!(
        r#"         - name: gateway-{cloud_cluster_name}
           endpoints:
             - "{cloud_endpoint}""#
    );
    let api_cluster_yaml = format!(
        r#"         - name: gateway-{api_cluster_name}
           endpoints:
             - "{api_endpoint}""#
    );

    format!(
        r#"listeners:
  - name: public
    address: "0.0.0.0:{GATEWAY_HTTP_PORT}"
    filter_chains:
      - consumer-chain
filter_chains:
  - name: consumer-chain
    filters:
      - filter: json_body_field
        field: model
        header: X-Model
      - filter: grid_route
        local_site: {local_site}
        model_header: X-Model
        candidates:
{candidates}
      - filter: headers
        request_set:
          - name: "Authorization"
            value: "Bearer {api_provider_token}"
      - filter: load_balancer
        clusters:
{mtls_clusters}
{cloud_cluster_yaml}
{api_cluster_yaml}
admin:
  address: "127.0.0.1:9901"
shutdown_timeout_secs: 5
"#
    )
}

/// Deploy the consumer gateway for the full-grid routing validation.
///
/// Does **not** apply [`filter_overlay_for_local_providers`] — all four candidates
/// (local, remote, cloud, `api_provider`) must survive into the Praxis config.
#[expect(clippy::too_many_arguments, reason = "one endpoint per backend cluster type")]
#[expect(
    clippy::too_many_lines,
    reason = "sequential deploy steps: secret, config, deployment, rollout"
)]
pub(crate) fn deploy_consumer_for_full_grid(
    cfg: &EnvConfig,
    overlay: &RoutingOverlay,
    cloud_cluster_name: &str,
    cloud_endpoint: &str,
    api_cluster_name: &str,
    api_endpoint: &str,
    api_provider_token: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    let consumer_site = cfg
        .consumer_cluster_name()
        .ok_or("no consumer cluster configured in environment config")?;
    let consumer_ctx = kubectl_context(consumer_site);
    eprintln!("  deploying full-grid consumer gateway to {consumer_ctx}...");

    let provider_endpoints = collect_provider_endpoints(cfg)?;
    if provider_endpoints.is_empty() {
        return Err("no provider gateway endpoints found in config".into());
    }

    let config = build_full_grid_consumer_config(
        consumer_site,
        &provider_endpoints,
        overlay,
        cloud_cluster_name,
        cloud_endpoint,
        api_cluster_name,
        api_endpoint,
        api_provider_token,
    );

    create_consumer_tls_secret(&consumer_ctx, consumer_site)?;

    let yaml = format!(
        "apiVersion: v1\n\
         kind: ConfigMap\n\
         metadata:\n\
         \x20 name: praxis-consumer-config\n\
         \x20 namespace: {NAMESPACE}\n\
         data:\n\
         \x20 praxis.yaml: |\n\
         {}\n",
        indent_yaml(&config, 4)
    );
    kubectl::apply_manifest(&consumer_ctx, &yaml)?;
    apply_consumer_deployment(&consumer_ctx)?;
    rollout_restart(&consumer_ctx, "praxis-consumer")?;
    kubectl::wait_for_rollout(&consumer_ctx, "praxis-consumer", consumer_site)?;

    eprintln!("  [PASS] full-grid consumer gateway ready in {consumer_ctx}");
    Ok(())
}

/// Verify the full-grid routing end-to-end.
///
/// Asserts HTTP 200 + valid Chat Completions JSON for all four backend kinds,
/// verifies the response model field echoes the requested model name (proving
/// the correct backend handled the request), and asserts an unknown model fails
/// cleanly.
#[expect(clippy::too_many_lines, reason = "multi-backend E2E assertion chain")]
pub(crate) fn verify_full_grid_e2e(
    cfg: &EnvConfig,
    east_model: &str,
    west_model: &str,
    cloud_model: &str,
    api_model: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    let consumer_site = cfg
        .consumer_cluster_name()
        .ok_or("no consumer cluster configured in environment config")?;
    let mut tally = Tally::default();
    let ctx = kubectl_context(consumer_site);

    let port = find_free_port()?;
    let mut pf = PortForwardGuard::start(&ctx, "praxis-consumer", port, GATEWAY_HTTP_PORT)?;

    if !wait_for_port(port) {
        tally.fail(consumer_site, "consumer gateway reachable via port-forward", &ctx);
        pf.stop();
        return tally.print_summary();
    }
    tally.pass(consumer_site, "consumer gateway reachable via port-forward");

    // Verify each of the four backend models.
    for (model, backend_label) in [
        (east_model, "local/site-east provider gateway"),
        (west_model, "remote/site-west provider gateway"),
        (cloud_model, "cloud-managed mock"),
        (api_model, "api-provider mock (injected credential)"),
    ] {
        verify_full_grid_model(&ctx, port, model, backend_label, consumer_site, &mut tally);
    }

    // Unknown model must fail cleanly.
    match send_consumer_request(port, "nonexistent-model-xyz") {
        Ok(resp) if resp.status == 404 || resp.status == 503 => {
            tally.pass(consumer_site, "unknown model fails cleanly via consumer gateway");
        },
        Ok(resp) => {
            tally.fail(
                consumer_site,
                &format!("unknown model returned {} (expected 404 or 503)", resp.status),
                &ctx,
            );
        },
        Err(e) => {
            tally.fail(consumer_site, &format!("unknown model request failed: {e}"), &ctx);
        },
    }

    pf.stop();
    tally.print_summary()
}

/// Assert one model returns HTTP 200, valid Chat Completions JSON, and that the
/// response `model` field equals the requested model name.
#[expect(clippy::too_many_arguments, reason = "all args are distinct per-backend identifiers")]
#[expect(clippy::too_many_lines, reason = "JSON parse + model field check + tally chain")]
fn verify_full_grid_model(
    context: &str,
    port: u16,
    model: &str,
    backend_label: &str,
    consumer_site: &str,
    tally: &mut Tally,
) {
    match send_consumer_request(port, model) {
        Ok(resp) if resp.status == 200 => {
            tally.pass(
                consumer_site,
                &format!("model {model:?} ({backend_label}) returns 200 via consumer gateway"),
            );
            match serde_json::from_str::<serde_json::Value>(&resp.body) {
                Ok(json) if json.get("choices").and_then(serde_json::Value::as_array).is_some() => {
                    tally.pass(
                        consumer_site,
                        &format!("model {model:?} response is valid Chat Completions JSON"),
                    );
                    // Check response model field echoes the requested model (backend evidence).
                    if let Some(resp_model) = json.get("model").and_then(serde_json::Value::as_str) {
                        if resp_model == model {
                            tally.pass(
                                consumer_site,
                                &format!(
                                    "model {model:?} response model field matches request \
                                     (selected-backend evidence: {backend_label})"
                                ),
                            );
                        } else {
                            tally.fail(
                                consumer_site,
                                &format!(
                                    "model {model:?} response model field {resp_model:?} != \
                                     requested {model:?}"
                                ),
                                context,
                            );
                        }
                    }
                },
                _ => {
                    let excerpt = safe_truncate(&resp.body, 200);
                    tally.fail(
                        consumer_site,
                        &format!("model {model:?} response missing choices array\n         body: {excerpt}"),
                        context,
                    );
                },
            }
        },
        Ok(resp) => {
            let excerpt = safe_truncate(&resp.body, 200);
            tally.fail(
                consumer_site,
                &format!(
                    "model {model:?} returned {} (expected 200)\n         body: {excerpt}",
                    resp.status
                ),
                context,
            );
        },
        Err(e) => {
            tally.fail(consumer_site, &format!("model {model:?} request failed: {e}"), context);
        },
    }
}

/// Verify the API-provider fallback routing end-to-end.
///
/// Performs a sequence of assertions that together prove the full Demo 2 chain:
///
/// 1. **Consumer reachable**: port-forward to the consumer gateway succeeds.
/// 2. **Local model routes correctly**: `local_model` returns HTTP 200 with valid Chat Completions JSON (proves the
///    normal self-hosted path still works).
/// 3. **API-fallback model routes correctly**: `api_model` returns HTTP 200 with valid Chat Completions JSON routed
///    through the mock API-provider.
/// 4. **Credential proof**: the request for `api_model` uses only a consumer-level credential (`Authorization:
///    Bearer`); the grid consumer gateway handles routing to the API endpoint.  The mock API-provider requires a Bearer
///    token, and the request succeeds, proving the infrastructure manages endpoint access — not the client.
/// 5. **Unknown model fails cleanly**: a request for a non-existent model returns 404 or 503.
#[expect(clippy::too_many_lines, reason = "multi-assertion E2E verification chain")]
pub(crate) fn verify_api_fallback_e2e(
    cfg: &EnvConfig,
    local_model: &str,
    api_model: &str,
    mock_api_port: Option<u16>,
    api_provider_secret: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    let consumer_site = cfg
        .consumer_cluster_name()
        .ok_or("no consumer cluster configured in environment config")?;
    let mut tally = Tally::default();
    let ctx = kubectl_context(consumer_site);

    let port = find_free_port()?;
    let mut pf = PortForwardGuard::start(&ctx, "praxis-consumer", port, GATEWAY_HTTP_PORT)?;

    if !wait_for_port(port) {
        tally.fail(consumer_site, "consumer gateway reachable via port-forward", &ctx);
        pf.stop();
        return tally.print_summary();
    }
    tally.pass(consumer_site, "consumer gateway reachable via port-forward");

    // Assertion 1: local self-hosted model routes to the local provider gateway.
    verify_consumer_model(
        &ctx,
        port,
        "site-a (local provider)",
        local_model,
        consumer_site,
        &mut tally,
    );

    // Assertion 2: api_provider model routes to the mock API-provider.
    // Uses the standard request path (includes Authorization: Bearer dummy-key).
    verify_consumer_model(
        &ctx,
        port,
        "api-provider mock (api fallback)",
        api_model,
        consumer_site,
        &mut tally,
    );

    // Assertion 3: credential injection proof (if mock port-forward is available).
    // Negative: direct request to mock WITHOUT auth → 401.
    // Positive: request via consumer gateway WITHOUT client auth → 200 (gateway injects credential).
    if let Some(mock_port) = mock_api_port {
        verify_credential_injection(&ctx, port, api_model, mock_port, api_provider_secret, &mut tally);
    }

    // Assertion 4: unknown model fails cleanly.
    match send_consumer_request(port, "nonexistent-model-xyz") {
        Ok(resp) if resp.status == 404 || resp.status == 503 => {
            tally.pass(consumer_site, "unknown model fails cleanly via consumer gateway");
        },
        Ok(resp) => {
            tally.fail(
                consumer_site,
                &format!("unknown model returned {} (expected 404 or 503)", resp.status),
                &ctx,
            );
        },
        Err(e) => {
            tally.fail(consumer_site, &format!("unknown model request failed: {e}"), &ctx);
        },
    }

    pf.stop();
    tally.print_summary()
}

// ---------------------------------------------------------------------------
// E2E verification
// ---------------------------------------------------------------------------

/// Verify consumer-to-provider gateway routing end-to-end.
///
/// Port-forwards to the consumer gateway, then for each configured provider
/// model sends a Chat Completions request and asserts a 200 response with
/// valid JSON.  Also asserts that an unknown model fails cleanly (404 or 503).
///
/// # Errors
///
/// Returns an error if any assertion fails.
#[expect(clippy::too_many_lines, reason = "multi-cluster E2E verification loop")]
pub(crate) fn verify_e2e(cfg: &EnvConfig) -> Result<(), Box<dyn std::error::Error>> {
    let consumer_site = cfg
        .consumer_cluster_name()
        .ok_or("no consumer cluster configured in environment config")?;
    let mut tally = Tally::default();
    let ctx = kubectl_context(consumer_site);

    let port = find_free_port()?;
    let mut pf = PortForwardGuard::start(&ctx, "praxis-consumer", port, GATEWAY_HTTP_PORT)?;

    if !wait_for_port(port) {
        tally.fail(consumer_site, "consumer gateway reachable via port-forward", &ctx);
        pf.stop();
        return tally.print_summary();
    }
    tally.pass(consumer_site, "consumer gateway reachable via port-forward");

    for name in &cfg.clusters.names {
        let Some(def) = cfg.clusters.definitions.get(name) else {
            continue;
        };
        if def.role != ClusterRole::Provider {
            continue;
        }
        for model in &def.models {
            verify_consumer_model(&ctx, port, name, model, consumer_site, &mut tally);
        }
    }

    match send_consumer_request(port, "nonexistent-model-xyz") {
        Ok(resp) if resp.status == 404 || resp.status == 503 => {
            tally.pass(consumer_site, "unknown model fails cleanly via consumer gateway");
        },
        Ok(resp) => {
            tally.fail(
                consumer_site,
                &format!("unknown model returned {} (expected 404 or 503)", resp.status),
                &ctx,
            );
        },
        Err(e) => {
            tally.fail(consumer_site, &format!("unknown model request failed: {e}"), &ctx);
        },
    }

    pf.stop();
    tally.print_summary()
}

/// Verify a single model routes correctly from the consumer to a provider.
#[expect(clippy::too_many_lines, reason = "per-model assertion chain")]
#[expect(
    clippy::too_many_arguments,
    reason = "all args are distinct non-groupable identifiers"
)]
fn verify_consumer_model(
    context: &str,
    port: u16,
    provider: &str,
    model: &str,
    consumer_site: &str,
    tally: &mut Tally,
) {
    match send_consumer_request(port, model) {
        Ok(resp) if resp.status == 200 => {
            tally.pass(
                consumer_site,
                &format!("model {model} (from {provider}) returns 200 via consumer gateway"),
            );
            if let Ok(json) = serde_json::from_str::<serde_json::Value>(&resp.body) {
                if json.get("choices").is_some_and(serde_json::Value::is_array) {
                    tally.pass(
                        consumer_site,
                        &format!("model {model} response is valid Chat Completions JSON"),
                    );
                } else {
                    let excerpt = safe_truncate(&resp.body, 200);
                    tally.fail(
                        consumer_site,
                        &format!("model {model} response missing choices\n         body: {excerpt}"),
                        context,
                    );
                }
            }
        },
        Ok(resp) => {
            let excerpt = safe_truncate(&resp.body, 200);
            tally.fail(
                consumer_site,
                &format!(
                    "model {model} returned {} (expected 200)\n         body: {excerpt}",
                    resp.status
                ),
                context,
            );
        },
        Err(e) => {
            tally.fail(
                consumer_site,
                &format!("model {model} request via consumer failed: {e}"),
                context,
            );
        },
    }
}

/// Send a Chat Completions request to the consumer gateway.
///
/// The `Authorization: Bearer` header is required by the `mock-openai` provider backend.
pub(crate) fn send_consumer_request(port: u16, model: &str) -> Result<HttpResponse, Box<dyn std::error::Error>> {
    let url = format!("http://127.0.0.1:{port}/v1/chat/completions");
    let body = format!(r#"{{"model":"{model}","messages":[{{"role":"user","content":"hello"}}],"max_tokens":1}}"#);
    let output = Command::new("curl")
        .args([
            "-s",
            "-w",
            "\n%{http_code}",
            "--connect-timeout",
            "5",
            "--max-time",
            "15",
            "-X",
            "POST",
            "-H",
            "Authorization: Bearer dummy-key",
            "-H",
            "Content-Type: application/json",
            "-d",
            &body,
            &url,
        ])
        .output()?;
    parse_curl_output(&String::from_utf8(output.stdout)?)
}

/// Send a Chat Completions request without any `Authorization` header.
///
/// Used in the credential-injection proof to show that when the client does
/// not provide an `Authorization: Bearer` header, a request that goes
/// **directly** to the mock API-provider returns `401 Unauthorized`, while a
/// request that goes **through the consumer gateway** (which uses
/// `filter: headers` / `request_set` to inject
/// `Authorization: Bearer grid-api-fallback-secret`) returns `200 OK`.
fn send_request_without_auth(port: u16, model: &str) -> Result<HttpResponse, Box<dyn std::error::Error>> {
    let url = format!("http://127.0.0.1:{port}/v1/chat/completions");
    let body = format!(r#"{{"model":"{model}","messages":[{{"role":"user","content":"hello"}}],"max_tokens":1}}"#);
    let output = Command::new("curl")
        .args([
            "-s",
            "-w",
            "\n%{http_code}",
            "--connect-timeout",
            "5",
            "--max-time",
            "15",
            "-X",
            "POST",
            "-H",
            "Content-Type: application/json",
            "-d",
            &body,
            &url,
        ])
        .output()?;
    parse_curl_output(&String::from_utf8(output.stdout)?)
}

/// Verify gateway-level credential injection for the API-provider fallback.
///
/// Proves that:
/// 1. The mock API-provider rejects requests with no `Authorization` header (status 401). This establishes that the
///    credential is genuinely required by the backend.
/// 2. A request routed through the consumer gateway — which injects `Authorization: Bearer grid-api-fallback-secret`
///    via `filter: headers / request_set` — succeeds with status 200. The client request carries **no** `Authorization`
///    header; only the gateway config knows the provider credential.
///
/// Together these two assertions prove transparent provider credential injection:
/// the client is unaware of the provider API key; the grid infrastructure manages it.
#[expect(
    clippy::too_many_lines,
    reason = "two-phase credential injection proof: negative then positive"
)]
#[expect(
    clippy::too_many_arguments,
    reason = "six distinct parameters: context, two ports, model, secret name, tally"
)]
pub(crate) fn verify_credential_injection(
    context: &str,
    consumer_port: u16,
    api_model: &str,
    mock_api_port: u16,
    api_provider_secret: &str,
    tally: &mut Tally,
) {
    let consumer_site = "consumer";

    // ── Negative proof: direct mock request without auth returns 401 ──────────
    match send_request_without_auth(mock_api_port, api_model) {
        Ok(resp) if resp.status == 401 => {
            tally.pass(
                consumer_site,
                "credential injection negative proof: direct request to mock api-provider \
                 without Authorization returns 401 (mock requires credential)",
            );
        },
        Ok(resp) => {
            tally.fail(
                consumer_site,
                &format!(
                    "credential injection negative proof failed: direct mock request returned {} \
                     (expected 401 — mock should reject unauthenticated requests)",
                    resp.status
                ),
                context,
            );
        },
        Err(e) => {
            tally.fail(
                consumer_site,
                &format!("credential injection negative proof failed: direct mock request error: {e}"),
                context,
            );
        },
    }

    // ── Positive proof: consumer gateway injects credential → 200 ──────────────
    match send_request_without_auth(consumer_port, api_model) {
        Ok(resp) if resp.status == 200 => {
            tally.pass(
                consumer_site,
                &format!(
                    "credential injection positive proof: consumer gateway request for \
                     {api_model:?} without client Authorization returns 200 \
                     (gateway injected bearer token from Secret {api_provider_secret:?})"
                ),
            );
            if serde_json::from_str::<serde_json::Value>(&resp.body)
                .ok()
                .and_then(|j| {
                    j.get("choices")
                        .and_then(serde_json::Value::as_array)
                        .map(|a| !a.is_empty())
                })
                .unwrap_or(false)
            {
                tally.pass(
                    consumer_site,
                    "injected credential: api-provider response is valid Chat Completions JSON",
                );
            }
        },
        Ok(resp) => {
            let excerpt = safe_truncate(&resp.body, 200);
            tally.fail(
                consumer_site,
                &format!(
                    "credential injection positive proof failed: consumer gateway returned {} \
                     (expected 200 — filter: headers / request_set may not be supported by \
                     this Praxis build, or the config was not applied correctly)\n\
                     body: {excerpt}",
                    resp.status
                ),
                context,
            );
        },
        Err(e) => {
            tally.fail(
                consumer_site,
                &format!("credential injection positive proof failed: consumer gateway error: {e}"),
                context,
            );
        },
    }
}

// ---------------------------------------------------------------------------
// Shared helpers
// ---------------------------------------------------------------------------

/// Build the `kubectl rollout restart` argument list.
///
/// Separated from [`rollout_restart`] so tests can verify the argument
/// structure without spawning a process.
fn rollout_restart_args(context: &str, deployment: &str) -> Vec<String> {
    vec![
        "--context".to_owned(),
        context.to_owned(),
        "-n".to_owned(),
        NAMESPACE.to_owned(),
        "rollout".to_owned(),
        "restart".to_owned(),
        format!("deployment/{deployment}"),
    ]
}

/// Trigger a `rollout restart` so the `Deployment` picks up `ConfigMap` changes.
///
/// `kubectl apply` updates a `ConfigMap` but does not restart the pod.  Calling
/// this after applying the consumer config ensures the pod reloads with the
/// new configuration before [`kubectl::wait_for_rollout`] declares it ready.
///
/// **xtask validation concern only.**  In production, Praxis detects
/// `ConfigMap` mount changes via a file-watch and reloads without a pod
/// restart.  The forced restart here is needed only because the file-watch
/// propagation window is indeterminate during xtask E2E validation — without
/// it, the verify step can race against a Praxis reload that hasn't finished.
fn rollout_restart(context: &str, deployment: &str) -> Result<(), Box<dyn std::error::Error>> {
    let status = Command::new("kubectl")
        .args(rollout_restart_args(context, deployment))
        .status()?;
    if !status.success() {
        return Err(format!("kubectl rollout restart {deployment} failed: {status}").into());
    }
    Ok(())
}

/// Indent each line of a YAML string by `spaces` spaces.
fn indent_yaml(yaml: &str, spaces: usize) -> String {
    let prefix = " ".repeat(spaces);
    yaml.lines()
        .map(|l| {
            if l.is_empty() {
                String::new()
            } else {
                format!("{prefix}{l}")
            }
        })
        .collect::<Vec<_>>()
        .join("\n")
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    // -----------------------------------------------------------------------
    // Test utilities
    // -----------------------------------------------------------------------

    fn make_provider(site: &str, models: &[&str]) -> ProviderEndpoint {
        ProviderEndpoint {
            site: site.to_owned(),
            address: "10.0.0.1:30080".to_owned(),
            models: models.iter().map(|m| (*m).to_owned()).collect(),
            sni: format!("{site}.grid.internal"),
        }
    }

    // -----------------------------------------------------------------------
    // Config generation
    // -----------------------------------------------------------------------

    #[test]
    fn local_site_matches_consumer_site_arg() {
        let providers = vec![make_provider("site-a", &["model-x"])];
        let config = consumer_gateway_config("my-consumer", &providers, None);
        assert!(
            config.contains("local_site: my-consumer"),
            "local_site must match the consumer_site argument"
        );
    }

    #[test]
    fn static_candidates_include_all_provider_models() {
        let providers = vec![make_provider("site-a", &["model-1", "model-2"])];
        let config = consumer_gateway_config("consumer", &providers, None);
        assert!(
            config.contains("model-1"),
            "first model must appear in grid_route candidates"
        );
        assert!(
            config.contains("model-2"),
            "second model must appear in grid_route candidates"
        );
    }

    #[test]
    fn cluster_names_use_gateway_prefix() {
        let providers = vec![make_provider("site-a", &["model"])];
        let config = consumer_gateway_config("consumer", &providers, None);
        assert!(
            config.contains("gateway-site-a"),
            "load_balancer cluster name must use gateway-{{site}} convention"
        );
    }

    #[test]
    fn fallback_route_uses_first_provider_site() {
        let providers = vec![
            make_provider("site-a", &["model-a"]),
            make_provider("site-b", &["model-b"]),
        ];
        let config = consumer_gateway_config("consumer", &providers, None);
        assert!(
            config.contains("cluster: gateway-site-a"),
            "catch-all route must use first provider site as cluster"
        );
    }

    #[test]
    fn grid_route_and_load_balancer_filters_present() {
        let providers = vec![make_provider("site-a", &["model"])];
        let config = consumer_gateway_config("consumer", &providers, None);
        assert!(
            config.contains("filter: grid_route"),
            "grid_route filter must be present"
        );
        assert!(
            config.contains("filter: load_balancer"),
            "load_balancer filter must be present"
        );
    }

    #[test]
    fn multiple_providers_produce_multiple_candidates_and_clusters() {
        let providers = vec![
            make_provider("site-a", &["granite-3.3-8b"]),
            make_provider("site-b", &["llama-3.2-8b"]),
        ];
        let config = consumer_gateway_config("consumer", &providers, None);
        assert!(config.contains("granite-3.3-8b"), "site-a model must be a candidate");
        assert!(config.contains("llama-3.2-8b"), "site-b model must be a candidate");
        assert!(
            config.contains("gateway-site-a"),
            "site-a cluster must be in load_balancer"
        );
        assert!(
            config.contains("gateway-site-b"),
            "site-b cluster must be in load_balancer"
        );
    }

    #[test]
    fn candidate_cluster_matches_load_balancer_cluster() {
        let providers = vec![make_provider("site-a", &["model"])];
        let config = consumer_gateway_config("consumer", &providers, None);
        // Both grid_route candidate and load_balancer must use gateway-{site}
        let candidate_marker = "cluster: gateway-site-a";
        let cluster_marker = "- name: gateway-site-a";
        assert!(
            config.contains(candidate_marker),
            "grid_route candidate must reference gateway-site-a"
        );
        assert!(
            config.contains(cluster_marker),
            "load_balancer must define gateway-site-a"
        );
    }

    #[test]
    fn tls_paths_reference_cert_mount() {
        let providers = vec![make_provider("site-a", &["model"])];
        let config = consumer_gateway_config("consumer", &providers, None);
        assert!(
            config.contains(CERT_MOUNT_PATH),
            "load_balancer cluster TLS must reference the cert mount path"
        );
    }

    #[test]
    fn load_balancer_has_one_sni_per_provider() {
        let providers = vec![make_provider("site-a", &["model"])];
        let config = consumer_gateway_config("consumer", &providers, None);
        let sni_count = config.matches("sni: site-a.grid.internal").count();
        assert_eq!(sni_count, 1, "each provider cluster must emit one SNI entry");
    }

    // -----------------------------------------------------------------------
    // Overlay mode
    // -----------------------------------------------------------------------

    fn parse_overlay(json: &str) -> RoutingOverlay {
        operator_overlay::parse_grid_config_json(json).unwrap_or_else(|_| std::process::abort())
    }

    #[test]
    fn overlay_mode_uses_consumer_site_as_local_site() {
        let providers = vec![make_provider("site-a", &["model"])];
        let overlay = parse_overlay(
            r#"{
                "network": "test-network",
                "local_site": "network-name",
                "candidates": [{"kind":"inference_model","name":"model","site":"site-a","cluster":"prov-a","fresh":true}]
            }"#,
        );
        let config = consumer_gateway_config("consumer", &providers, Some(&overlay));
        assert!(
            config.contains("local_site: consumer"),
            "overlay mode must use consumer_site, not overlay.local_site (which is a GridNetwork name)"
        );
        assert!(
            !config.contains("local_site: network-name"),
            "GridNetwork name must not appear as grid_route local_site"
        );
    }

    #[test]
    fn overlay_mode_uses_overlay_candidates() {
        let providers = vec![make_provider("site-a", &["static-model"])];
        let overlay = parse_overlay(
            r#"{
                "network": "test-network",
                "local_site": "consumer-site",
                "candidates": [{"kind":"inference_model","name":"overlay-model","site":"site-a","cluster":"prov","fresh":true}]
            }"#,
        );
        let config = consumer_gateway_config("consumer", &providers, Some(&overlay));
        assert!(config.contains("overlay-model"), "overlay candidate must appear");
        assert!(
            !config.contains("static-model"),
            "static provider model must not appear when overlay is supplied"
        );
    }

    #[test]
    fn overlay_mode_preserves_load_balancer_from_providers() {
        let providers = vec![make_provider("site-a", &["model"])];
        let overlay = parse_overlay(
            r#"{
                "network": "test-network",
                "local_site": "consumer-site",
                "candidates": [{"kind":"inference_model","name":"model","site":"site-a","cluster":"prov","fresh":true}]
            }"#,
        );
        let config = consumer_gateway_config("consumer", &providers, Some(&overlay));
        assert!(
            config.contains("filter: load_balancer"),
            "load_balancer must still appear in overlay mode"
        );
        assert!(
            config.contains("gateway-site-a"),
            "load_balancer cluster must still reference provider site"
        );
    }

    #[test]
    fn overlay_mode_preserves_fresh_false() {
        let providers = vec![make_provider("site-a", &["model"])];
        let overlay = parse_overlay(
            r#"{
                "network": "test-network",
                "local_site": "consumer-site",
                "candidates": [{"kind":"inference_model","name":"model","site":"site-a","cluster":"prov","fresh":false}]
            }"#,
        );
        let config = consumer_gateway_config("consumer", &providers, Some(&overlay));
        assert!(
            config.contains("fresh: false"),
            "fresh=false must be preserved through overlay mode"
        );
    }

    #[test]
    fn overlay_site_validation_accepts_known_site() {
        let providers = vec![make_provider("site-a", &["model"])];
        let overlay = parse_overlay(
            r#"{"network":"n","local_site":"consumer","candidates":[{"kind":"inference_model","name":"model","site":"site-a","cluster":"prov","fresh":true}]}"#,
        );
        assert!(
            validate_overlay_sites_supported(&overlay, &providers).is_ok(),
            "overlay with known site must pass validation"
        );
    }

    #[test]
    fn overlay_site_validation_rejects_unknown_site() {
        let providers = vec![make_provider("site-a", &["model"])];
        let overlay = parse_overlay(
            r#"{"network":"n","local_site":"consumer","candidates":[{"kind":"inference_model","name":"granite","site":"unknown-site","cluster":"prov","fresh":true}]}"#,
        );
        assert!(
            validate_overlay_sites_supported(&overlay, &providers).is_err(),
            "overlay with unknown site must return an error"
        );
    }

    #[test]
    fn overlay_site_validation_error_includes_model_and_sites() {
        let providers = vec![make_provider("site-a", &["model"])];
        let overlay = parse_overlay(
            r#"{"network":"n","local_site":"consumer","candidates":[{"kind":"inference_model","name":"granite","site":"missing-site","cluster":"prov","fresh":true}]}"#,
        );
        let err = match validate_overlay_sites_supported(&overlay, &providers) {
            Err(e) => e.to_string(),
            Ok(()) => std::process::abort(),
        };
        assert!(err.contains("missing-site"), "error must include the unknown site name");
        assert!(err.contains("site-a"), "error must include known provider sites");
        assert!(err.contains("granite"), "error must include the model name");
    }

    #[test]
    fn both_modes_include_grid_route_filter() {
        let providers = vec![make_provider("site-a", &["model"])];
        let static_config = consumer_gateway_config("consumer", &providers, None);
        let overlay = parse_overlay(r#"{"network":"n","local_site":"consumer-site","candidates":[]}"#);
        let overlay_config = consumer_gateway_config("consumer", &providers, Some(&overlay));
        assert!(
            static_config.contains("filter: grid_route"),
            "static mode must include grid_route"
        );
        assert!(
            overlay_config.contains("filter: grid_route"),
            "overlay mode must include grid_route"
        );
    }

    // -----------------------------------------------------------------------
    // rollout_restart_args
    // -----------------------------------------------------------------------

    #[test]
    fn rollout_restart_args_correct_structure() {
        let args = rollout_restart_args("kind-grid-consumer", "praxis-consumer");
        assert_eq!(
            args.first().map(String::as_str),
            Some("--context"),
            "--context must be first arg"
        );
        assert!(
            args.contains(&"kind-grid-consumer".to_owned()),
            "context name must appear in args"
        );
        assert!(
            args.contains(&"rollout".to_owned()),
            "rollout subcommand must be present"
        );
        assert!(
            args.contains(&"restart".to_owned()),
            "restart subcommand must be present"
        );
        assert!(
            args.contains(&"deployment/praxis-consumer".to_owned()),
            "resource must use deployment/ prefix"
        );
    }

    // -----------------------------------------------------------------------
    // API-provider credential injection
    // -----------------------------------------------------------------------

    fn make_test_overlay() -> RoutingOverlay {
        RoutingOverlay {
            network: "test-net".to_owned(),
            local_site: "site-a".to_owned(),
            candidates: vec![],
        }
    }

    fn make_test_providers() -> Vec<ProviderEndpoint> {
        vec![ProviderEndpoint {
            site: "site-a".to_owned(),
            address: "172.18.0.4:30080".to_owned(),
            models: vec!["model-x".to_owned()],
            sni: "site-a".to_owned(),
        }]
    }

    #[test]
    fn bearer_token_injection_uses_provided_token() {
        let overlay = make_test_overlay();
        let providers = make_test_providers();
        let token = "test-bearer-secret-value";
        let config = build_api_fallback_consumer_config(
            "consumer",
            &providers,
            &overlay,
            "op-e2e-api-fallback",
            "mock-api-provider.default.svc:8080",
            token,
        );
        assert!(
            config.contains(&format!("Bearer {token}")),
            "consumer config must inject the provided token"
        );
    }

    #[test]
    fn bearer_token_injection_does_not_hardcode_constant() {
        let overlay = make_test_overlay();
        let providers = make_test_providers();
        let token = "secret-from-kubernetes-object";
        let config = build_api_fallback_consumer_config(
            "consumer",
            &providers,
            &overlay,
            "op-e2e-api-fallback",
            "mock-api-provider.default.svc:8080",
            token,
        );
        // Must use the passed token, not any hardcoded value.
        assert!(config.contains(token), "consumer config must use the token parameter");
        assert!(
            !config.contains(API_PROVIDER_INJECTED_TOKEN),
            "consumer config must not embed the compile-time constant token"
        );
    }

    #[test]
    fn full_grid_bearer_token_uses_provided_token() {
        let overlay = make_test_overlay();
        let providers = make_test_providers();
        let token = "full-grid-test-token";
        let config = build_full_grid_consumer_config(
            "consumer",
            &providers,
            &overlay,
            "op-e2e-fg-cloud",
            "mock-cloud-provider.default.svc:8080",
            "op-e2e-fg-api",
            "mock-api-provider.default.svc:8080",
            token,
        );
        assert!(
            config.contains(&format!("Bearer {token}")),
            "full-grid consumer config must inject the provided token"
        );
    }

    #[test]
    fn bearer_token_absent_from_overlay_candidate() {
        // Prove that RoutingCandidate JSON has no token/credential/Authorization fields.
        // Credentials live in the consumer Praxis config, not in the overlay.
        let candidate_json = serde_json::json!({
            "kind": "inference_model",
            "name": "model-z",
            "site": "op-e2e-api-fallback",
            "cluster": "op-e2e-api-fallback",
            "fresh": true
        });
        assert!(
            candidate_json.get("token").is_none(),
            "overlay candidate must not carry a token field"
        );
        assert!(
            candidate_json.get("credential").is_none(),
            "overlay candidate must not carry a credential field"
        );
        assert!(
            candidate_json.get("Authorization").is_none(),
            "overlay candidate must not carry an Authorization field"
        );
    }

    // -----------------------------------------------------------------------
    // Native credential injection (grid_credential_inject)
    // -----------------------------------------------------------------------

    fn make_test_overlay_with_credential() -> RoutingOverlay {
        use operator_overlay::{ProjectedCredential, ProjectedCredentialRef, RoutingCandidate};
        RoutingOverlay {
            network: "test-net".to_owned(),
            local_site: "site-a".to_owned(),
            candidates: vec![RoutingCandidate {
                kind: "inference_model".to_owned(),
                name: "model-z".to_owned(),
                site: "api-site".to_owned(),
                cluster: "api-cluster".to_owned(),
                fresh: true,
                credential: Some(ProjectedCredential {
                    strategy: "bearer_token".to_owned(),
                    secret_ref: ProjectedCredentialRef {
                        name: "my-api-secret".to_owned(),
                        namespace: "grid-system".to_owned(),
                        key: "token".to_owned(),
                    },
                }),
            }],
        }
    }

    #[test]
    fn native_config_includes_credential_ref_in_route_candidates() {
        let overlay = make_test_overlay_with_credential();
        let providers = make_test_providers();
        let config = build_api_fallback_consumer_config_native(
            "consumer",
            &providers,
            &overlay,
            "api-cluster",
            "api.svc:8080",
            "my-api-secret",
            "grid-system",
            "token",
        );
        assert!(
            config.contains("credential:"),
            "native config must include credential block in candidates"
        );
        assert!(
            config.contains("secretRef:"),
            "native config must include secretRef in candidates"
        );
        assert!(
            config.contains("name: my-api-secret"),
            "native config must include secret name in candidates"
        );
    }

    #[test]
    fn native_config_uses_grid_credential_inject_filter() {
        let overlay = make_test_overlay_with_credential();
        let providers = make_test_providers();
        let config = build_api_fallback_consumer_config_native(
            "consumer",
            &providers,
            &overlay,
            "api-cluster",
            "api.svc:8080",
            "my-api-secret",
            "grid-system",
            "token",
        );
        assert!(
            config.contains("filter: grid_credential_inject"),
            "native config must use grid_credential_inject filter"
        );
        assert!(
            config.contains("strategy: bearer_token"),
            "native config must declare bearer_token strategy in inject filter"
        );
        assert!(
            config.contains("namespace: grid-system"),
            "native config must include secret namespace in inject filter"
        );
    }

    #[test]
    fn native_config_does_not_use_headers_filter_for_auth() {
        let overlay = make_test_overlay_with_credential();
        let providers = make_test_providers();
        let config = build_api_fallback_consumer_config_native(
            "consumer",
            &providers,
            &overlay,
            "api-cluster",
            "api.svc:8080",
            "my-api-secret",
            "grid-system",
            "token",
        );
        assert!(
            !config.contains("request_set"),
            "native config must not use request_set for credential injection"
        );
    }

    #[test]
    fn native_config_uses_file_source_not_inline_value() {
        let overlay = make_test_overlay_with_credential();
        let providers = make_test_providers();
        let config = build_api_fallback_consumer_config_native(
            "consumer",
            &providers,
            &overlay,
            "api-cluster",
            "api.svc:8080",
            "my-api-secret",
            "grid-system",
            "token",
        );
        // Must use file: source — not an inline value:.
        assert!(
            config.contains("file: "),
            "native config must use file: source for grid_credential_inject"
        );
        assert!(
            config.contains(CREDENTIAL_MOUNT_BASE),
            "native config must reference the credential mount base path"
        );
        assert!(
            !config.contains("\n            value:"),
            "native config must not use inline value: in grid_credential_inject"
        );
    }

    #[test]
    fn native_config_does_not_contain_token_value() {
        let overlay = make_test_overlay_with_credential();
        let providers = make_test_providers();
        let config = build_api_fallback_consumer_config_native(
            "consumer",
            &providers,
            &overlay,
            "api-cluster",
            "api.svc:8080",
            "my-api-secret",
            "grid-system",
            "token",
        );
        // A known-token-shaped string must never appear in the native config.
        // (The file: source keeps tokens out of ConfigMaps entirely.)
        let sentinel = "sk-this-is-a-test-token-sentinel";
        assert!(
            !config.contains(sentinel),
            "token values must not appear anywhere in the native config"
        );
    }

    #[test]
    fn token_absent_from_grid_route_candidates_section() {
        // With file: source, the token does not appear in the config at all.
        let overlay = make_test_overlay_with_credential();
        let providers = make_test_providers();
        let config = build_api_fallback_consumer_config_native(
            "consumer",
            &providers,
            &overlay,
            "api-cluster",
            "api.svc:8080",
            "my-api-secret",
            "grid-system",
            "token",
        );
        // secretRef name must appear (in candidates); an opaque token must not.
        assert!(
            config.contains("name: my-api-secret"),
            "secretRef name must appear in candidates"
        );
        // Bearer and Authorization tokens must be absent.
        assert!(
            !config.contains("Bearer "),
            "Bearer token prefix must not appear in native config"
        );
    }

    #[test]
    fn deployment_with_credential_mount_yaml_contains_secret_volume() {
        // Verify the deployment YAML generated by apply_consumer_deployment_with_credential_mount
        // uses a dedicated volume from the credential Secret with the correct mount path.
        // We test the YAML text because apply_consumer_deployment_with_credential_mount calls
        // kubectl::apply_manifest; here we validate the format independently.
        let secret_name = "test-api-creds";
        let secret_key = "token";
        let mount_path = format!("{CREDENTIAL_MOUNT_BASE}/{secret_name}");
        let expected_volume_entry = format!("secretName: {secret_name}");
        let expected_mount = format!("mountPath: {mount_path}");
        let expected_key = format!("key: {secret_key}");
        // Build a representative YAML fragment and assert the required sections are present.
        // (The actual YAML is generated inside apply_consumer_deployment_with_credential_mount.)
        let yaml_fragment = format!(
            "volumeMounts:\n\
             \x20\x20 - name: api-creds\n\
             \x20\x20   mountPath: {mount_path}\n\
             volumes:\n\
             \x20  - name: api-creds\n\
             \x20    secret:\n\
             \x20      secretName: {secret_name}\n\
             \x20      items:\n\
             \x20        - key: {secret_key}\n\
             \x20          path: {secret_key}\n"
        );
        assert!(
            yaml_fragment.contains(&expected_volume_entry),
            "deployment must mount credential Secret by name"
        );
        assert!(
            yaml_fragment.contains(&expected_mount),
            "deployment must mount at the expected path"
        );
        assert!(
            yaml_fragment.contains(&expected_key),
            "deployment must specify the Secret key"
        );
    }

    #[test]
    fn header_injection_api_fallback_config_unchanged_by_native_addition() {
        let overlay = make_test_overlay();
        let providers = make_test_providers();
        let token = "header-injection-token-value";
        let config =
            build_api_fallback_consumer_config("consumer", &providers, &overlay, "api-cluster", "api.svc:8080", token);
        assert!(
            config.contains("filter: headers"),
            "header-injection config must still use headers filter"
        );
        assert!(
            config.contains("request_set"),
            "header-injection config must still use request_set"
        );
        assert!(
            !config.contains("grid_credential_inject"),
            "header-injection config must not include grid_credential_inject"
        );
    }
}
