//! Certificate provider trait and static file implementation.

use std::path::{Path, PathBuf};

// ---------------------------------------------------------------------------
// Error
// ---------------------------------------------------------------------------

/// Errors from certificate providers.
#[derive(Debug, thiserror::Error)]
pub enum ProviderError {
    /// Failed to read a certificate file.
    #[error("failed to read certificate file {path}: {source}")]
    ReadFile {
        /// Path that failed to read.
        path: PathBuf,
        /// Underlying IO error.
        source: std::io::Error,
    },
}

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/// A site's TLS certificate and private key.
#[derive(Debug, Clone)]
pub struct SiteCertificate {
    /// PEM-encoded certificate chain.
    pub cert_pem: String,

    /// PEM-encoded private key.
    pub key_pem: String,

    /// Subject Alternative Names on this certificate.
    pub sans: Vec<String>,
}

/// Trust bundle containing CA certificates for all grid sites.
#[derive(Debug, Clone)]
pub struct TrustBundle {
    /// PEM-encoded CA certificates (concatenated).
    pub ca_pem: String,
}

// ---------------------------------------------------------------------------
// Trait
// ---------------------------------------------------------------------------

/// Abstraction over certificate sourcing.
///
/// The POC uses [`StaticFileProvider`] (certs from disk).
/// Production will use a `SpiffeProvider` (SPIRE workload API)
/// that receives short-lived X.509 SVIDs with automatic rotation.
///
/// The mTLS connection layer takes a `Box<dyn CertificateProvider>`
/// and is agnostic to the source.
pub trait CertificateProvider: Send + Sync {
    /// Load the site certificate and private key.
    ///
    /// # Errors
    ///
    /// Returns [`ProviderError`] if the certificate cannot be loaded.
    fn site_certificate(&self) -> Result<SiteCertificate, ProviderError>;

    /// Load the trust bundle (CA certificates for all grid sites).
    ///
    /// # Errors
    ///
    /// Returns [`ProviderError`] if the trust bundle cannot be loaded.
    fn trust_bundle(&self) -> Result<TrustBundle, ProviderError>;
}

// ---------------------------------------------------------------------------
// Static file provider
// ---------------------------------------------------------------------------

/// Loads certificates from files on disk.
///
/// Used for POC and testing. Certificates are generated by the
/// xtask at environment setup time using [`rcgen`].
#[derive(Debug)]
pub struct StaticFileProvider {
    /// Path to the PEM-encoded site certificate.
    cert_path: PathBuf,

    /// Path to the PEM-encoded private key.
    key_path: PathBuf,

    /// Path to the PEM-encoded CA certificate (trust bundle).
    ca_path: PathBuf,

    /// SANs to report (stored at generation time).
    sans: Vec<String>,
}

impl StaticFileProvider {
    /// Create a new provider from file paths.
    pub fn new(cert_path: PathBuf, key_path: PathBuf, ca_path: PathBuf, sans: Vec<String>) -> Self {
        Self {
            cert_path,
            key_path,
            ca_path,
            sans,
        }
    }
}

impl CertificateProvider for StaticFileProvider {
    fn site_certificate(&self) -> Result<SiteCertificate, ProviderError> {
        let cert_pem = read_file(&self.cert_path)?;
        let key_pem = read_file(&self.key_path)?;
        Ok(SiteCertificate {
            cert_pem,
            key_pem,
            sans: self.sans.clone(),
        })
    }

    fn trust_bundle(&self) -> Result<TrustBundle, ProviderError> {
        let ca_pem = read_file(&self.ca_path)?;
        Ok(TrustBundle { ca_pem })
    }
}

// ---------------------------------------------------------------------------
// Private helpers
// ---------------------------------------------------------------------------

/// Read a file to a string.
fn read_file(path: &Path) -> Result<String, ProviderError> {
    std::fs::read_to_string(path).map_err(|source| ProviderError::ReadFile {
        path: path.to_owned(),
        source,
    })
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use std::io::Write as _;

    use super::*;

    #[test]
    fn static_provider_loads_files() {
        let dir = std::env::temp_dir().join("grid-certs-test-load");
        std::fs::create_dir_all(&dir).unwrap_or_default();

        let cert_path = dir.join("cert.pem");
        let key_path = dir.join("key.pem");
        let ca_path = dir.join("ca.pem");

        write_file(&cert_path, "CERT-DATA");
        write_file(&key_path, "KEY-DATA");
        write_file(&ca_path, "CA-DATA");

        let provider =
            StaticFileProvider::new(cert_path, key_path, ca_path, vec!["cluster-a.grid.internal".to_owned()]);

        let cert = provider.site_certificate();
        assert!(cert.is_ok(), "should load certificate");
        let cert = cert.unwrap_or_else(|_| std::process::abort());
        assert_eq!(cert.cert_pem, "CERT-DATA", "cert content mismatch");
        assert_eq!(cert.key_pem, "KEY-DATA", "key content mismatch");
        assert_eq!(cert.sans.len(), 1, "should have 1 SAN");

        let bundle = provider.trust_bundle();
        assert!(bundle.is_ok(), "should load trust bundle");
        let bundle = bundle.unwrap_or_else(|_| std::process::abort());
        assert_eq!(bundle.ca_pem, "CA-DATA", "CA content mismatch");

        let _cleanup = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn static_provider_missing_file() {
        let provider = StaticFileProvider::new(
            PathBuf::from("/nonexistent/cert.pem"),
            PathBuf::from("/nonexistent/key.pem"),
            PathBuf::from("/nonexistent/ca.pem"),
            vec![],
        );

        let result = provider.site_certificate();
        assert!(result.is_err(), "should fail on missing file");
        let msg = result.err().map(|e| e.to_string()).unwrap_or_default();
        assert!(msg.contains("nonexistent"), "error should reference the path: {msg}");
    }

    /// Write test data to a file.
    fn write_file(path: &Path, content: &str) {
        let mut f = std::fs::File::create(path).unwrap_or_else(|_| std::process::abort());
        f.write_all(content.as_bytes()).unwrap_or_default();
    }
}
