//! SWIM transport encryption for the AI Grid.
//!
//! All SWIM gossip messages — foca protocol bytes and [`crate::StateBroadcast`]
//! payloads — are encrypted and authenticated with AES-256-GCM when the runtime
//! has a configured key.  The cipher provides:
//!
//! - **Confidentiality**: membership packets, gateway addresses, and public certificate PEM broadcasts are not readable
//!   by observers without the key.
//! - **Authentication**: a wrong-key or tampered packet fails the GCM tag verification and is silently dropped; the
//!   SWIM state machine never sees it.
//! - **Nonce uniqueness**: each packet uses 12 cryptographically random bytes generated by the OS RNG, making nonce
//!   reuse negligibly unlikely.
//!
//! # Wire format
//!
//! ```text
//! ┌──────────┬─────────┬──────────────┬──────────────────────────────┐
//! │ MAGIC    │ VERSION │ NONCE        │ CIPHERTEXT + GCM TAG         │
//! │ 4 bytes  │ 1 byte  │ 12 bytes     │ plaintext.len() + 16 bytes   │
//! │ b"GRID"  │ 0x01    │ random       │ AES-256-GCM AEAD output      │
//! └──────────┴─────────┴──────────────┴──────────────────────────────┘
//! ```
//!
//! Total overhead per packet: 33 bytes.
//!
//! # Security properties
//!
//! - **Wrong key**: `decrypt` returns `CryptoError::AuthFailed`; the packet is dropped silently.
//! - **Tampered ciphertext**: same — GCM tag fails, packet dropped.
//! - **Plaintext packet with key configured**: the receive path checks the magic header first.  A packet without the
//!   `b"GRID"` prefix returns `CryptoError::BadMagic` and is dropped.
//! - **No key configured**: the encrypt/decrypt paths in the runtime are not called at all; plaintext behavior is
//!   preserved.
//!
//! # AAD (Additional Authenticated Data)
//!
//! AAD is intentionally empty.  The SWIM runtime is process-global and all peers
//! that share the same key are expected to communicate.  Per-network label
//! isolation requires separate per-network key dispatch.
//!
//! # Key rotation
//!
//! Key replacement technically takes effect immediately, but safe rotation
//! requires a coordinated restart or simultaneous replacement across sites
//! because there is no multi-key keyring.

use aes_gcm::{
    Aes256Gcm, Key, Nonce,
    aead::{Aead as _, AeadCore as _, KeyInit as _, OsRng},
};

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/// Magic bytes that prefix every encrypted Grid SWIM packet.
///
/// Allows the receive path to quickly distinguish encrypted from plaintext
/// without attempting a full decrypt.
pub const MAGIC: [u8; 4] = *b"GRID";

/// Encrypted packet version.  Bump if the wire format changes.
pub const ENCRYPTED_VERSION: u8 = 0x01_u8;

/// Nonce length for AES-256-GCM (12 bytes).
pub const NONCE_LEN: usize = 12;

/// GCM authentication tag length (16 bytes).
pub const TAG_LEN: usize = 16;

/// Per-packet overhead: 4 (magic) + 1 (version) + 12 (nonce) + 16 (tag).
pub const OVERHEAD: usize = 4 + 1 + NONCE_LEN + TAG_LEN;

/// AES-256-GCM key: exactly 32 bytes.
pub type SwimKey = [u8; 32];

// ---------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------

/// Error returned by [`decrypt`].
///
/// The caller should drop the packet silently on any variant.  No variant
/// should be logged with payload content — the error message is safe to
/// emit at `warn` or `debug` level.
#[derive(Debug, thiserror::Error)]
pub enum CryptoError {
    /// Packet is shorter than the minimum encrypted frame.
    #[error("packet too short for encrypted SWIM frame (need >= {OVERHEAD} bytes)")]
    TooShort,

    /// First 4 bytes do not match `b\"GRID\"`.
    ///
    /// Either a plaintext foca packet (no encryption configured on sender) or
    /// traffic from a non-Grid process.
    #[error("packet does not carry Grid SWIM magic header")]
    BadMagic,

    /// Version byte is not [`ENCRYPTED_VERSION`].
    #[error("encrypted SWIM packet has unknown version {0:#04x}")]
    UnknownVersion(u8),

    /// AES-256-GCM authentication tag verification failed.
    ///
    /// Most commonly caused by a wrong key.  Tampered ciphertext produces the
    /// same error — GCM does not distinguish between the two cases.
    #[error("SWIM packet authentication failed (wrong key or tampered data)")]
    AuthFailed,
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// Encrypt a SWIM UDP payload with AES-256-GCM.
///
/// Returns the encrypted frame including the [`MAGIC`] prefix, version byte,
/// random nonce, ciphertext, and 16-byte GCM tag.  The nonce is generated from
/// the OS RNG so repeated calls produce distinct ciphertexts.
#[must_use]
pub fn encrypt(key: &SwimKey, plaintext: &[u8]) -> Vec<u8> {
    let cipher = Aes256Gcm::new(Key::<Aes256Gcm>::from_slice(key));
    let nonce = Aes256Gcm::generate_nonce(OsRng);
    // AES-256-GCM encrypt is infallible once the cipher and nonce are valid.
    let ciphertext = cipher
        .encrypt(&nonce, plaintext)
        .unwrap_or_else(|_| std::process::abort());

    let mut out = Vec::with_capacity(OVERHEAD + plaintext.len());
    out.extend_from_slice(&MAGIC);
    out.push(ENCRYPTED_VERSION);
    out.extend_from_slice(&nonce);
    out.extend_from_slice(&ciphertext);
    out
}

/// Decrypt and authenticate a SWIM UDP payload.
///
/// Validates the magic prefix and version, then runs AES-256-GCM AEAD
/// authentication and decryption.  Returns the plaintext on success.
///
/// # Errors
///
/// Returns [`CryptoError`] on any parse or authentication failure.  The caller
/// must drop the packet silently without logging the raw bytes.
pub fn decrypt(key: &SwimKey, data: &[u8]) -> Result<Vec<u8>, CryptoError> {
    if data.len() < OVERHEAD {
        return Err(CryptoError::TooShort);
    }
    // Use .get() throughout to satisfy the workspace indexing_slicing lint.
    // All of these unwraps succeed because we've already checked data.len() >= OVERHEAD.
    let magic = data.get(..4).ok_or(CryptoError::TooShort)?;
    if magic != MAGIC {
        return Err(CryptoError::BadMagic);
    }
    let version = data.get(4).copied().ok_or(CryptoError::TooShort)?;
    if version != ENCRYPTED_VERSION {
        return Err(CryptoError::UnknownVersion(version));
    }
    let nonce_bytes = data.get(5..17).ok_or(CryptoError::TooShort)?;
    let ciphertext = data.get(17..).ok_or(CryptoError::TooShort)?;

    let nonce = Nonce::from_slice(nonce_bytes);
    let cipher = Aes256Gcm::new(Key::<Aes256Gcm>::from_slice(key));
    cipher.decrypt(nonce, ciphertext).map_err(|_e| CryptoError::AuthFailed)
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn test_key(seed: u8) -> SwimKey {
        [seed; 32]
    }

    const PLAINTEXT: &[u8] = b"hello SWIM";

    #[test]
    fn encrypt_then_decrypt_round_trip() {
        let key = test_key(0x42);
        let ciphertext = encrypt(&key, PLAINTEXT);
        let recovered = decrypt(&key, &ciphertext).unwrap_or_else(|_| std::process::abort());
        assert_eq!(recovered, PLAINTEXT, "decrypted payload must match original");
    }

    #[test]
    fn wrong_key_fails() {
        let key_a = test_key(0x01);
        let key_b = test_key(0x02);
        let ciphertext = encrypt(&key_a, PLAINTEXT);
        assert!(
            matches!(decrypt(&key_b, &ciphertext), Err(CryptoError::AuthFailed)),
            "wrong key must produce AuthFailed"
        );
    }

    #[test]
    fn tampered_ciphertext_fails() {
        let key = test_key(0x07);
        let mut ciphertext = encrypt(&key, PLAINTEXT);
        // Flip a bit in the ciphertext body (past the 17-byte header).
        // Using get_mut to satisfy indexing_slicing lint.
        if let Some(b) = ciphertext.get_mut(20) {
            *b ^= 0xFF;
        }
        assert!(
            matches!(decrypt(&key, &ciphertext), Err(CryptoError::AuthFailed)),
            "tampered ciphertext must produce AuthFailed"
        );
    }

    #[test]
    fn plaintext_packet_rejected_bad_magic() {
        let key = test_key(0x99);
        // Use a packet that is >= OVERHEAD bytes long but does not start with the
        // GRID magic header.  Packets shorter than OVERHEAD return TooShort first.
        let plaintext_packet = b"not encrypted foca bytes --- long enough foca packet here";
        assert!(
            plaintext_packet.len() >= OVERHEAD,
            "test input must be long enough to reach the magic check"
        );
        assert!(
            matches!(decrypt(&key, plaintext_packet), Err(CryptoError::BadMagic)),
            "plaintext packet long enough for magic check must produce BadMagic"
        );
    }

    #[test]
    fn short_plaintext_packet_rejected_too_short() {
        let key = test_key(0x99);
        let short_packet = b"short";
        assert!(
            matches!(decrypt(&key, short_packet), Err(CryptoError::TooShort)),
            "short plaintext packet must produce TooShort"
        );
    }

    #[test]
    fn too_short_packet_fails() {
        let key = test_key(0x11);
        assert!(
            matches!(decrypt(&key, &[0_u8; 10]), Err(CryptoError::TooShort)),
            "short packet must produce TooShort"
        );
    }

    #[test]
    fn unknown_version_fails() {
        let key = test_key(0x55);
        let mut ciphertext = encrypt(&key, PLAINTEXT);
        if let Some(b) = ciphertext.get_mut(4) {
            *b = 0xFF;
        }
        assert!(
            matches!(decrypt(&key, &ciphertext), Err(CryptoError::UnknownVersion(0xFF))),
            "unknown version must produce UnknownVersion"
        );
    }

    #[test]
    fn empty_plaintext_round_trips() {
        let key = test_key(0x00);
        let ciphertext = encrypt(&key, b"");
        let recovered = decrypt(&key, &ciphertext).unwrap_or_else(|_| std::process::abort());
        assert!(recovered.is_empty(), "empty plaintext decrypts to empty");
    }

    #[test]
    fn nonces_differ_across_encryptions() {
        let key = test_key(0xAB);
        let c1 = encrypt(&key, PLAINTEXT);
        let c2 = encrypt(&key, PLAINTEXT);
        let nonce1 = c1.get(5..17).unwrap_or_else(|| std::process::abort());
        let nonce2 = c2.get(5..17).unwrap_or_else(|| std::process::abort());
        assert_ne!(nonce1, nonce2, "repeated encryptions must produce distinct nonces");
        assert_eq!(decrypt(&key, &c1).unwrap_or_else(|_| std::process::abort()), PLAINTEXT);
        assert_eq!(decrypt(&key, &c2).unwrap_or_else(|_| std::process::abort()), PLAINTEXT);
    }

    #[test]
    fn ciphertext_does_not_contain_plaintext() {
        let key = test_key(0xDE);
        let plaintext = b"secret provider state";
        let ciphertext = encrypt(&key, plaintext);
        let tag_start = ciphertext.len().saturating_sub(TAG_LEN);
        let body = ciphertext.get(17..tag_start).unwrap_or_else(|| std::process::abort());
        assert!(
            !body.windows(plaintext.len()).any(|w| w == plaintext),
            "ciphertext body must not contain the plaintext"
        );
    }

    #[test]
    fn wrong_magic_byte_produces_bad_magic() {
        let key = test_key(0x13);
        let mut ciphertext = encrypt(&key, PLAINTEXT);
        if let Some(b) = ciphertext.get_mut(0) {
            *b ^= 0x01;
        }
        assert!(
            matches!(decrypt(&key, &ciphertext), Err(CryptoError::BadMagic)),
            "corrupted magic must produce BadMagic"
        );
    }

    #[test]
    fn wire_format_structure() {
        let key = test_key(0x77);
        let ciphertext = encrypt(&key, PLAINTEXT);
        assert_eq!(
            ciphertext.get(..4).unwrap_or_else(|| std::process::abort()),
            b"GRID",
            "first 4 bytes must be magic"
        );
        assert_eq!(
            ciphertext.get(4).copied().unwrap_or_else(|| std::process::abort()),
            ENCRYPTED_VERSION,
            "byte 4 must be version"
        );
        assert_eq!(
            ciphertext.len(),
            OVERHEAD + PLAINTEXT.len(),
            "total length must be OVERHEAD + plaintext length"
        );
    }
}
