//! High-level SWIM node wrapping a [`foca::Foca`] instance.
//!
//! [`SwimNode`] encapsulates all foca internals — codec, RNG, and the
//! [`GridRuntime`] adapter — so callers only interact with the Grid-specific
//! [`AccumulatedOutput`] and [`MemberEvent`] types.
//!
//! The runtime is **not** thread-safe; callers must drive the event loop from
//! a single task (see `operator::swim_runtime`).

use std::time::Duration;

use rand::{SeedableRng as _, rngs::SmallRng};
use tokio::sync::mpsc;

use crate::{AccumulatedOutput, GridRuntime, MemberEvent, NodeId, runtime::TimerEvent};

// ---------------------------------------------------------------------------
// Internal type aliases
// ---------------------------------------------------------------------------

/// The concrete foca Foca type used by the grid.
///
/// Using `BincodeCodec` with the standard bincode 2.x config provides
/// compact, backward-compatible serialization for SWIM gossip messages.
/// `SmallRng` is adequate for gossip-target randomization; this is not
/// a cryptographic use.
type GridFoca =
    foca::Foca<NodeId, foca::BincodeCodec<bincode::config::Configuration>, SmallRng, foca::NoCustomBroadcast>;

// ---------------------------------------------------------------------------
// SwimNode
// ---------------------------------------------------------------------------

/// A ready-to-drive SWIM node.
///
/// Wraps a [`foca::Foca`] instance together with a [`GridRuntime`] adapter.
/// Callers drive the node by feeding incoming UDP bytes and timer events;
/// after each call, [`AccumulatedOutput`] contains UDP messages to send and
/// timers to schedule.
///
/// The node is not `Send` or `Sync` on its own; run it from a single tokio
/// task and pass only [`AccumulatedOutput`] across task boundaries.
pub struct SwimNode {
    /// The foca membership instance.
    foca: GridFoca,

    /// The runtime adapter that accumulates foca's side effects.
    runtime: GridRuntime,
}

impl SwimNode {
    /// Create a new SWIM node with the given identity.
    ///
    /// Membership events are forwarded to `event_tx`.  The caller may
    /// process events from [`AccumulatedOutput::events`] instead; the
    /// channel is a secondary delivery path for subscribers that want
    /// immediate notification.
    pub fn new(identity: NodeId, event_tx: mpsc::Sender<MemberEvent>) -> Self {
        let seed = {
            // Truncate nanoseconds to u64; we want spread, not precision.
            #[expect(
                clippy::cast_possible_truncation,
                reason = "intentional truncation for entropy mixing"
            )]
            let nanos = std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap_or(Duration::ZERO)
                .as_nanos() as u64;
            // XOR with a process-startup-derived constant so two nodes starting
            // at the exact same nanosecond still diverge.
            let port = u64::from(identity.socket_addr().port());
            nanos ^ port.wrapping_mul(0x9E37_79B9_7F4A_7C15)
        };
        let rng = SmallRng::seed_from_u64(seed);
        let codec = foca::BincodeCodec(bincode::config::standard());
        Self {
            foca: foca::Foca::new(identity, foca::Config::simple(), rng, codec),
            runtime: GridRuntime::new(event_tx),
        }
    }

    /// Feed an incoming UDP packet to foca.
    ///
    /// Returns all accumulated side effects: outbound UDP messages, scheduled
    /// timers, and membership events generated by processing this packet.
    /// Parse or protocol errors are logged at `warn` level and do not abort
    /// the returned output.
    pub fn handle_data(&mut self, data: &[u8]) -> AccumulatedOutput {
        if let Err(e) = self.foca.handle_data(data, &mut self.runtime) {
            tracing::warn!(error = %e, len = data.len(), "foca handle_data error");
        }
        self.runtime.take_output()
    }

    /// Deliver a scheduled timer event to foca.
    ///
    /// Only [`TimerEvent::Token`] events are forwarded to foca; all other
    /// variants are silently ignored (they were removed or never implemented
    /// in this codec).
    pub fn handle_timer(&mut self, event: TimerEvent) -> AccumulatedOutput {
        if let TimerEvent::Token(t) = event
            && let Err(e) = self.foca.handle_timer(t, &mut self.runtime)
        {
            tracing::warn!(error = %e, "foca handle_timer error");
        }
        self.runtime.take_output()
    }

    /// Announce this node to a known peer, requesting membership inclusion.
    ///
    /// This is the SWIM join handshake.  Call once per seed peer at startup.
    /// Errors are logged at `warn` level.
    pub fn announce(&mut self, dst: NodeId) -> AccumulatedOutput {
        if let Err(e) = self.foca.announce(dst, &mut self.runtime) {
            tracing::warn!(error = %e, "foca announce error");
        }
        self.runtime.take_output()
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use tokio::sync::mpsc;

    use super::*;

    fn local_id(port: u16) -> NodeId {
        NodeId::new(
            format!("test-{port}"),
            format!("127.0.0.1:{port}")
                .parse()
                .unwrap_or_else(|_| std::process::abort()),
        )
    }

    #[test]
    fn new_creates_node_without_panic() {
        let (tx, _rx) = mpsc::channel(1);
        let id = local_id(19_001);
        let _node = SwimNode::new(id, tx);
    }

    #[test]
    fn handle_data_with_garbage_returns_empty_output() {
        let (tx, _rx) = mpsc::channel(1);
        let mut node = SwimNode::new(local_id(19_002), tx);
        let output = node.handle_data(b"not-swim-data");
        // garbage is an error at the foca level; output is empty (no members to probe)
        assert!(
            output.messages.is_empty(),
            "garbage data should produce no outbound messages"
        );
    }

    #[test]
    fn handle_timer_with_unrecognised_variant_returns_empty() {
        let (tx, _rx) = mpsc::channel(1);
        let mut node = SwimNode::new(local_id(19_003), tx);
        let output = node.handle_timer(TimerEvent::PeriodicAnnounce);
        assert!(output.is_empty(), "non-Token timer variant should produce no output");
    }

    #[test]
    fn announce_to_self_returns_output() {
        let (tx, _rx) = mpsc::channel(1);
        let id = local_id(19_004);
        let mut node = SwimNode::new(id.clone(), tx);
        let output = node.announce(id);
        // Announcing to self is a protocol no-op; foca may or may not produce messages.
        // The important thing is that it does not panic.
        drop(output);
    }

    #[test]
    fn two_nodes_can_be_created_concurrently() {
        let (tx1, _rx1) = mpsc::channel(1);
        let (tx2, _rx2) = mpsc::channel(1);
        let node1 = SwimNode::new(local_id(19_005), tx1);
        let node2 = SwimNode::new(local_id(19_006), tx2);
        drop((node1, node2));
    }
}
