{{- if .Values.gridNetwork.name }}
apiVersion: grid.praxis-proxy.io/v1alpha1
kind: GridNetwork
metadata:
  name: {{ .Values.gridNetwork.name }}
  labels:
    {{- include "grid-site.labels" . | nindent 4 }}
spec:
  {{- with .Values.gridNetwork.gridId }}
  gridId: {{ . | quote }}
  {{- end }}
  {{- with .Values.gridNetwork.region }}
  region: {{ . | quote }}
  {{- end }}
  {{- with .Values.gridNetwork.zone }}
  zone: {{ . | quote }}
  {{- end }}
  {{- with .Values.gridNetwork.routingPolicy }}
  routingPolicy: {{ . | quote }}
  {{- end }}
  {{- with .Values.gridNetwork.scoringPolicy }}
  {{- if .strategy }}
  scoringPolicy:
    strategy: {{ .strategy | quote }}
  {{- end }}
  {{- end }}
  {{- with .Values.gridNetwork.metricsRefreshInterval }}
  {{- if . }}
  metricsRefreshInterval: {{ . | quote }}
  {{- end }}
  {{- end }}
  {{- with .Values.gridNetwork.swim }}
  swim:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.gridNetwork.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.gridNetwork.gatewayRefs }}
  gatewayRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
