{{- if .Values.overlay.configMapName }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "praxis-gateway.fullname" . }}-overlay-sync
  labels:
    {{- include "praxis-gateway.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
