apiVersion: v1
kind: Service
metadata:
  name: gtm-emulator
  namespace: grid-system
  labels:
    app.kubernetes.io/name: gtm-emulator
    app.kubernetes.io/part-of: grid-glb-demo
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: gtm-emulator
  ports:
    - name: https
      port: 8443
      targetPort: https
